/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FromLandingRouteImport } from './routes/from-landing'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AccountRemovedRouteImport } from './routes/account/removed'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin-settings'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as LoginEmailIndexRouteImport } from './routes/login/email/index'
import { Route as AuthenticatedPricingIndexRouteImport } from './routes/_authenticated/pricing/index'
import { Route as LoginEmailVerifyRouteImport } from './routes/login/email/verify'
import { Route as LoginEmailSentRouteImport } from './routes/login/email/sent'
import { Route as AuthenticatedRedirectToCheckOutPlanIntervalRouteImport } from './routes/_authenticated/redirect-to-check-out/$planInterval'
import { Route as AuthenticatedProfileDangerZoneRouteImport } from './routes/_authenticated/profile/danger-zone'
import { Route as AuthenticatedPricingFreeTrialExplanationRouteImport } from './routes/_authenticated/pricing/free-trial-explanation'
import { Route as AuthenticatedPricingCheckoutSuccessRouteImport } from './routes/_authenticated/pricing/checkout-success'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/_app/settings'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/_app/profile'
import { Route as AuthenticatedAppSessionsIndexRouteImport } from './routes/_authenticated/_app/sessions/index'
import { Route as AuthenticatedAppSessionsNewRouteImport } from './routes/_authenticated/_app/sessions/new'
import { Route as AuthenticatedAppSessionsSessionIdIndexRouteImport } from './routes/_authenticated/_app/sessions/$sessionId/index'
import { Route as AuthenticatedAppSessionsSessionIdProcessingRouteImport } from './routes/_authenticated/_app/sessions/$sessionId/processing'
import { Route as AuthenticatedAppSessionsSessionIdReviewIndexRouteImport } from './routes/_authenticated/_app/sessions/$sessionId/review/index'
import { Route as AuthenticatedAppSessionsSessionIdReviewCardIdRouteImport } from './routes/_authenticated/_app/sessions/$sessionId/review/$cardId'

const FromLandingRoute = FromLandingRouteImport.update({
  id: '/from-landing',
  path: '/from-landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRemovedRoute = AccountRemovedRouteImport.update({
  id: '/account/removed',
  path: '/account/removed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin-settings',
    path: '/admin-settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LoginEmailIndexRoute = LoginEmailIndexRouteImport.update({
  id: '/login/email/',
  path: '/login/email/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPricingIndexRoute =
  AuthenticatedPricingIndexRouteImport.update({
    id: '/pricing/',
    path: '/pricing/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LoginEmailVerifyRoute = LoginEmailVerifyRouteImport.update({
  id: '/login/email/verify',
  path: '/login/email/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginEmailSentRoute = LoginEmailSentRouteImport.update({
  id: '/login/email/sent',
  path: '/login/email/sent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRedirectToCheckOutPlanIntervalRoute =
  AuthenticatedRedirectToCheckOutPlanIntervalRouteImport.update({
    id: '/redirect-to-check-out/$planInterval',
    path: '/redirect-to-check-out/$planInterval',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileDangerZoneRoute =
  AuthenticatedProfileDangerZoneRouteImport.update({
    id: '/profile/danger-zone',
    path: '/profile/danger-zone',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPricingFreeTrialExplanationRoute =
  AuthenticatedPricingFreeTrialExplanationRouteImport.update({
    id: '/pricing/free-trial-explanation',
    path: '/pricing/free-trial-explanation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPricingCheckoutSuccessRoute =
  AuthenticatedPricingCheckoutSuccessRouteImport.update({
    id: '/pricing/checkout-success',
    path: '/pricing/checkout-success',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSessionsIndexRoute =
  AuthenticatedAppSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSessionsNewRoute =
  AuthenticatedAppSessionsNewRouteImport.update({
    id: '/sessions/new',
    path: '/sessions/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSessionsSessionIdIndexRoute =
  AuthenticatedAppSessionsSessionIdIndexRouteImport.update({
    id: '/sessions/$sessionId/',
    path: '/sessions/$sessionId/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSessionsSessionIdProcessingRoute =
  AuthenticatedAppSessionsSessionIdProcessingRouteImport.update({
    id: '/sessions/$sessionId/processing',
    path: '/sessions/$sessionId/processing',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSessionsSessionIdReviewIndexRoute =
  AuthenticatedAppSessionsSessionIdReviewIndexRouteImport.update({
    id: '/sessions/$sessionId/review/',
    path: '/sessions/$sessionId/review/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSessionsSessionIdReviewCardIdRoute =
  AuthenticatedAppSessionsSessionIdReviewCardIdRouteImport.update({
    id: '/sessions/$sessionId/review/$cardId',
    path: '/sessions/$sessionId/review/$cardId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/from-landing': typeof FromLandingRoute
  '/admin-settings': typeof AuthenticatedAdminSettingsRoute
  '/account/removed': typeof AccountRemovedRoute
  '/login/': typeof LoginIndexRoute
  '/profile': typeof AuthenticatedAppProfileRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/pricing/checkout-success': typeof AuthenticatedPricingCheckoutSuccessRoute
  '/pricing/free-trial-explanation': typeof AuthenticatedPricingFreeTrialExplanationRoute
  '/profile/danger-zone': typeof AuthenticatedProfileDangerZoneRoute
  '/redirect-to-check-out/$planInterval': typeof AuthenticatedRedirectToCheckOutPlanIntervalRoute
  '/login/email/sent': typeof LoginEmailSentRoute
  '/login/email/verify': typeof LoginEmailVerifyRoute
  '/pricing/': typeof AuthenticatedPricingIndexRoute
  '/login/email/': typeof LoginEmailIndexRoute
  '/sessions/new': typeof AuthenticatedAppSessionsNewRoute
  '/sessions/': typeof AuthenticatedAppSessionsIndexRoute
  '/sessions/$sessionId/processing': typeof AuthenticatedAppSessionsSessionIdProcessingRoute
  '/sessions/$sessionId/': typeof AuthenticatedAppSessionsSessionIdIndexRoute
  '/sessions/$sessionId/review/$cardId': typeof AuthenticatedAppSessionsSessionIdReviewCardIdRoute
  '/sessions/$sessionId/review/': typeof AuthenticatedAppSessionsSessionIdReviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/from-landing': typeof FromLandingRoute
  '/admin-settings': typeof AuthenticatedAdminSettingsRoute
  '/account/removed': typeof AccountRemovedRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof AuthenticatedAppProfileRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/pricing/checkout-success': typeof AuthenticatedPricingCheckoutSuccessRoute
  '/pricing/free-trial-explanation': typeof AuthenticatedPricingFreeTrialExplanationRoute
  '/profile/danger-zone': typeof AuthenticatedProfileDangerZoneRoute
  '/redirect-to-check-out/$planInterval': typeof AuthenticatedRedirectToCheckOutPlanIntervalRoute
  '/login/email/sent': typeof LoginEmailSentRoute
  '/login/email/verify': typeof LoginEmailVerifyRoute
  '/pricing': typeof AuthenticatedPricingIndexRoute
  '/login/email': typeof LoginEmailIndexRoute
  '/sessions/new': typeof AuthenticatedAppSessionsNewRoute
  '/sessions': typeof AuthenticatedAppSessionsIndexRoute
  '/sessions/$sessionId/processing': typeof AuthenticatedAppSessionsSessionIdProcessingRoute
  '/sessions/$sessionId': typeof AuthenticatedAppSessionsSessionIdIndexRoute
  '/sessions/$sessionId/review/$cardId': typeof AuthenticatedAppSessionsSessionIdReviewCardIdRoute
  '/sessions/$sessionId/review': typeof AuthenticatedAppSessionsSessionIdReviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/from-landing': typeof FromLandingRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/admin-settings': typeof AuthenticatedAdminSettingsRoute
  '/account/removed': typeof AccountRemovedRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/_app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/_app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/pricing/checkout-success': typeof AuthenticatedPricingCheckoutSuccessRoute
  '/_authenticated/pricing/free-trial-explanation': typeof AuthenticatedPricingFreeTrialExplanationRoute
  '/_authenticated/profile/danger-zone': typeof AuthenticatedProfileDangerZoneRoute
  '/_authenticated/redirect-to-check-out/$planInterval': typeof AuthenticatedRedirectToCheckOutPlanIntervalRoute
  '/login/email/sent': typeof LoginEmailSentRoute
  '/login/email/verify': typeof LoginEmailVerifyRoute
  '/_authenticated/pricing/': typeof AuthenticatedPricingIndexRoute
  '/login/email/': typeof LoginEmailIndexRoute
  '/_authenticated/_app/sessions/new': typeof AuthenticatedAppSessionsNewRoute
  '/_authenticated/_app/sessions/': typeof AuthenticatedAppSessionsIndexRoute
  '/_authenticated/_app/sessions/$sessionId/processing': typeof AuthenticatedAppSessionsSessionIdProcessingRoute
  '/_authenticated/_app/sessions/$sessionId/': typeof AuthenticatedAppSessionsSessionIdIndexRoute
  '/_authenticated/_app/sessions/$sessionId/review/$cardId': typeof AuthenticatedAppSessionsSessionIdReviewCardIdRoute
  '/_authenticated/_app/sessions/$sessionId/review/': typeof AuthenticatedAppSessionsSessionIdReviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/from-landing'
    | '/admin-settings'
    | '/account/removed'
    | '/login/'
    | '/profile'
    | '/settings'
    | '/pricing/checkout-success'
    | '/pricing/free-trial-explanation'
    | '/profile/danger-zone'
    | '/redirect-to-check-out/$planInterval'
    | '/login/email/sent'
    | '/login/email/verify'
    | '/pricing/'
    | '/login/email/'
    | '/sessions/new'
    | '/sessions/'
    | '/sessions/$sessionId/processing'
    | '/sessions/$sessionId/'
    | '/sessions/$sessionId/review/$cardId'
    | '/sessions/$sessionId/review/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/from-landing'
    | '/admin-settings'
    | '/account/removed'
    | '/login'
    | '/profile'
    | '/settings'
    | '/pricing/checkout-success'
    | '/pricing/free-trial-explanation'
    | '/profile/danger-zone'
    | '/redirect-to-check-out/$planInterval'
    | '/login/email/sent'
    | '/login/email/verify'
    | '/pricing'
    | '/login/email'
    | '/sessions/new'
    | '/sessions'
    | '/sessions/$sessionId/processing'
    | '/sessions/$sessionId'
    | '/sessions/$sessionId/review/$cardId'
    | '/sessions/$sessionId/review'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/from-landing'
    | '/_authenticated/_app'
    | '/_authenticated/admin-settings'
    | '/account/removed'
    | '/login/'
    | '/_authenticated/_app/profile'
    | '/_authenticated/_app/settings'
    | '/_authenticated/pricing/checkout-success'
    | '/_authenticated/pricing/free-trial-explanation'
    | '/_authenticated/profile/danger-zone'
    | '/_authenticated/redirect-to-check-out/$planInterval'
    | '/login/email/sent'
    | '/login/email/verify'
    | '/_authenticated/pricing/'
    | '/login/email/'
    | '/_authenticated/_app/sessions/new'
    | '/_authenticated/_app/sessions/'
    | '/_authenticated/_app/sessions/$sessionId/processing'
    | '/_authenticated/_app/sessions/$sessionId/'
    | '/_authenticated/_app/sessions/$sessionId/review/$cardId'
    | '/_authenticated/_app/sessions/$sessionId/review/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  FromLandingRoute: typeof FromLandingRoute
  AccountRemovedRoute: typeof AccountRemovedRoute
  LoginIndexRoute: typeof LoginIndexRoute
  LoginEmailSentRoute: typeof LoginEmailSentRoute
  LoginEmailVerifyRoute: typeof LoginEmailVerifyRoute
  LoginEmailIndexRoute: typeof LoginEmailIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/from-landing': {
      id: '/from-landing'
      path: '/from-landing'
      fullPath: '/from-landing'
      preLoaderRoute: typeof FromLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/removed': {
      id: '/account/removed'
      path: '/account/removed'
      fullPath: '/account/removed'
      preLoaderRoute: typeof AccountRemovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin-settings': {
      id: '/_authenticated/admin-settings'
      path: '/admin-settings'
      fullPath: '/admin-settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/login/email/': {
      id: '/login/email/'
      path: '/login/email'
      fullPath: '/login/email/'
      preLoaderRoute: typeof LoginEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pricing/': {
      id: '/_authenticated/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof AuthenticatedPricingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/login/email/verify': {
      id: '/login/email/verify'
      path: '/login/email/verify'
      fullPath: '/login/email/verify'
      preLoaderRoute: typeof LoginEmailVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/email/sent': {
      id: '/login/email/sent'
      path: '/login/email/sent'
      fullPath: '/login/email/sent'
      preLoaderRoute: typeof LoginEmailSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/redirect-to-check-out/$planInterval': {
      id: '/_authenticated/redirect-to-check-out/$planInterval'
      path: '/redirect-to-check-out/$planInterval'
      fullPath: '/redirect-to-check-out/$planInterval'
      preLoaderRoute: typeof AuthenticatedRedirectToCheckOutPlanIntervalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/danger-zone': {
      id: '/_authenticated/profile/danger-zone'
      path: '/profile/danger-zone'
      fullPath: '/profile/danger-zone'
      preLoaderRoute: typeof AuthenticatedProfileDangerZoneRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pricing/free-trial-explanation': {
      id: '/_authenticated/pricing/free-trial-explanation'
      path: '/pricing/free-trial-explanation'
      fullPath: '/pricing/free-trial-explanation'
      preLoaderRoute: typeof AuthenticatedPricingFreeTrialExplanationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pricing/checkout-success': {
      id: '/_authenticated/pricing/checkout-success'
      path: '/pricing/checkout-success'
      fullPath: '/pricing/checkout-success'
      preLoaderRoute: typeof AuthenticatedPricingCheckoutSuccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app/settings': {
      id: '/_authenticated/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/profile': {
      id: '/_authenticated/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/sessions/': {
      id: '/_authenticated/_app/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AuthenticatedAppSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/sessions/new': {
      id: '/_authenticated/_app/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof AuthenticatedAppSessionsNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/sessions/$sessionId/': {
      id: '/_authenticated/_app/sessions/$sessionId/'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId/'
      preLoaderRoute: typeof AuthenticatedAppSessionsSessionIdIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/sessions/$sessionId/processing': {
      id: '/_authenticated/_app/sessions/$sessionId/processing'
      path: '/sessions/$sessionId/processing'
      fullPath: '/sessions/$sessionId/processing'
      preLoaderRoute: typeof AuthenticatedAppSessionsSessionIdProcessingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/sessions/$sessionId/review/': {
      id: '/_authenticated/_app/sessions/$sessionId/review/'
      path: '/sessions/$sessionId/review'
      fullPath: '/sessions/$sessionId/review/'
      preLoaderRoute: typeof AuthenticatedAppSessionsSessionIdReviewIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/sessions/$sessionId/review/$cardId': {
      id: '/_authenticated/_app/sessions/$sessionId/review/$cardId'
      path: '/sessions/$sessionId/review/$cardId'
      fullPath: '/sessions/$sessionId/review/$cardId'
      preLoaderRoute: typeof AuthenticatedAppSessionsSessionIdReviewCardIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppSessionsNewRoute: typeof AuthenticatedAppSessionsNewRoute
  AuthenticatedAppSessionsIndexRoute: typeof AuthenticatedAppSessionsIndexRoute
  AuthenticatedAppSessionsSessionIdProcessingRoute: typeof AuthenticatedAppSessionsSessionIdProcessingRoute
  AuthenticatedAppSessionsSessionIdIndexRoute: typeof AuthenticatedAppSessionsSessionIdIndexRoute
  AuthenticatedAppSessionsSessionIdReviewCardIdRoute: typeof AuthenticatedAppSessionsSessionIdReviewCardIdRoute
  AuthenticatedAppSessionsSessionIdReviewIndexRoute: typeof AuthenticatedAppSessionsSessionIdReviewIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppSessionsNewRoute: AuthenticatedAppSessionsNewRoute,
  AuthenticatedAppSessionsIndexRoute: AuthenticatedAppSessionsIndexRoute,
  AuthenticatedAppSessionsSessionIdProcessingRoute:
    AuthenticatedAppSessionsSessionIdProcessingRoute,
  AuthenticatedAppSessionsSessionIdIndexRoute:
    AuthenticatedAppSessionsSessionIdIndexRoute,
  AuthenticatedAppSessionsSessionIdReviewCardIdRoute:
    AuthenticatedAppSessionsSessionIdReviewCardIdRoute,
  AuthenticatedAppSessionsSessionIdReviewIndexRoute:
    AuthenticatedAppSessionsSessionIdReviewIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedPricingCheckoutSuccessRoute: typeof AuthenticatedPricingCheckoutSuccessRoute
  AuthenticatedPricingFreeTrialExplanationRoute: typeof AuthenticatedPricingFreeTrialExplanationRoute
  AuthenticatedProfileDangerZoneRoute: typeof AuthenticatedProfileDangerZoneRoute
  AuthenticatedRedirectToCheckOutPlanIntervalRoute: typeof AuthenticatedRedirectToCheckOutPlanIntervalRoute
  AuthenticatedPricingIndexRoute: typeof AuthenticatedPricingIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedPricingCheckoutSuccessRoute:
    AuthenticatedPricingCheckoutSuccessRoute,
  AuthenticatedPricingFreeTrialExplanationRoute:
    AuthenticatedPricingFreeTrialExplanationRoute,
  AuthenticatedProfileDangerZoneRoute: AuthenticatedProfileDangerZoneRoute,
  AuthenticatedRedirectToCheckOutPlanIntervalRoute:
    AuthenticatedRedirectToCheckOutPlanIntervalRoute,
  AuthenticatedPricingIndexRoute: AuthenticatedPricingIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  FromLandingRoute: FromLandingRoute,
  AccountRemovedRoute: AccountRemovedRoute,
  LoginIndexRoute: LoginIndexRoute,
  LoginEmailSentRoute: LoginEmailSentRoute,
  LoginEmailVerifyRoute: LoginEmailVerifyRoute,
  LoginEmailIndexRoute: LoginEmailIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
