/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FromLandingRouteImport } from './routes/from-landing'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AccountRemovedRouteImport } from './routes/account/removed'
import { Route as AuthenticatedPremiumDemoRouteImport } from './routes/_authenticated/premium-demo'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin-settings'
import { Route as AuthenticatedTabsRouteImport } from './routes/_authenticated/_tabs'
import { Route as LoginEmailIndexRouteImport } from './routes/login/email/index'
import { Route as AuthenticatedPricingIndexRouteImport } from './routes/_authenticated/pricing/index'
import { Route as LoginEmailVerifyRouteImport } from './routes/login/email/verify'
import { Route as LoginEmailSentRouteImport } from './routes/login/email/sent'
import { Route as AuthenticatedRedirectToCheckOutPlanIntervalRouteImport } from './routes/_authenticated/redirect-to-check-out/$planInterval'
import { Route as AuthenticatedProfileDangerZoneRouteImport } from './routes/_authenticated/profile/danger-zone'
import { Route as AuthenticatedPricingFreeTrialExplanationRouteImport } from './routes/_authenticated/pricing/free-trial-explanation'
import { Route as AuthenticatedPricingCheckoutSuccessRouteImport } from './routes/_authenticated/pricing/checkout-success'
import { Route as AuthenticatedTabsProfileRouteImport } from './routes/_authenticated/_tabs/profile'
import { Route as AuthenticatedTabsHomeRouteImport } from './routes/_authenticated/_tabs/home'
import { Route as AuthenticatedTabsDashboardRouteImport } from './routes/_authenticated/_tabs/dashboard'

const FromLandingRoute = FromLandingRouteImport.update({
  id: '/from-landing',
  path: '/from-landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRemovedRoute = AccountRemovedRouteImport.update({
  id: '/account/removed',
  path: '/account/removed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPremiumDemoRoute =
  AuthenticatedPremiumDemoRouteImport.update({
    id: '/premium-demo',
    path: '/premium-demo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin-settings',
    path: '/admin-settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTabsRoute = AuthenticatedTabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LoginEmailIndexRoute = LoginEmailIndexRouteImport.update({
  id: '/login/email/',
  path: '/login/email/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPricingIndexRoute =
  AuthenticatedPricingIndexRouteImport.update({
    id: '/pricing/',
    path: '/pricing/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LoginEmailVerifyRoute = LoginEmailVerifyRouteImport.update({
  id: '/login/email/verify',
  path: '/login/email/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginEmailSentRoute = LoginEmailSentRouteImport.update({
  id: '/login/email/sent',
  path: '/login/email/sent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRedirectToCheckOutPlanIntervalRoute =
  AuthenticatedRedirectToCheckOutPlanIntervalRouteImport.update({
    id: '/redirect-to-check-out/$planInterval',
    path: '/redirect-to-check-out/$planInterval',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileDangerZoneRoute =
  AuthenticatedProfileDangerZoneRouteImport.update({
    id: '/profile/danger-zone',
    path: '/profile/danger-zone',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPricingFreeTrialExplanationRoute =
  AuthenticatedPricingFreeTrialExplanationRouteImport.update({
    id: '/pricing/free-trial-explanation',
    path: '/pricing/free-trial-explanation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPricingCheckoutSuccessRoute =
  AuthenticatedPricingCheckoutSuccessRouteImport.update({
    id: '/pricing/checkout-success',
    path: '/pricing/checkout-success',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTabsProfileRoute =
  AuthenticatedTabsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedTabsRoute,
  } as any)
const AuthenticatedTabsHomeRoute = AuthenticatedTabsHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedTabsRoute,
} as any)
const AuthenticatedTabsDashboardRoute =
  AuthenticatedTabsDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedTabsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/from-landing': typeof FromLandingRoute
  '/admin-settings': typeof AuthenticatedAdminSettingsRoute
  '/premium-demo': typeof AuthenticatedPremiumDemoRoute
  '/account/removed': typeof AccountRemovedRoute
  '/login/': typeof LoginIndexRoute
  '/dashboard': typeof AuthenticatedTabsDashboardRoute
  '/home': typeof AuthenticatedTabsHomeRoute
  '/profile': typeof AuthenticatedTabsProfileRoute
  '/pricing/checkout-success': typeof AuthenticatedPricingCheckoutSuccessRoute
  '/pricing/free-trial-explanation': typeof AuthenticatedPricingFreeTrialExplanationRoute
  '/profile/danger-zone': typeof AuthenticatedProfileDangerZoneRoute
  '/redirect-to-check-out/$planInterval': typeof AuthenticatedRedirectToCheckOutPlanIntervalRoute
  '/login/email/sent': typeof LoginEmailSentRoute
  '/login/email/verify': typeof LoginEmailVerifyRoute
  '/pricing/': typeof AuthenticatedPricingIndexRoute
  '/login/email/': typeof LoginEmailIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/from-landing': typeof FromLandingRoute
  '/admin-settings': typeof AuthenticatedAdminSettingsRoute
  '/premium-demo': typeof AuthenticatedPremiumDemoRoute
  '/account/removed': typeof AccountRemovedRoute
  '/login': typeof LoginIndexRoute
  '/dashboard': typeof AuthenticatedTabsDashboardRoute
  '/home': typeof AuthenticatedTabsHomeRoute
  '/profile': typeof AuthenticatedTabsProfileRoute
  '/pricing/checkout-success': typeof AuthenticatedPricingCheckoutSuccessRoute
  '/pricing/free-trial-explanation': typeof AuthenticatedPricingFreeTrialExplanationRoute
  '/profile/danger-zone': typeof AuthenticatedProfileDangerZoneRoute
  '/redirect-to-check-out/$planInterval': typeof AuthenticatedRedirectToCheckOutPlanIntervalRoute
  '/login/email/sent': typeof LoginEmailSentRoute
  '/login/email/verify': typeof LoginEmailVerifyRoute
  '/pricing': typeof AuthenticatedPricingIndexRoute
  '/login/email': typeof LoginEmailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/from-landing': typeof FromLandingRoute
  '/_authenticated/_tabs': typeof AuthenticatedTabsRouteWithChildren
  '/_authenticated/admin-settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/premium-demo': typeof AuthenticatedPremiumDemoRoute
  '/account/removed': typeof AccountRemovedRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/_tabs/dashboard': typeof AuthenticatedTabsDashboardRoute
  '/_authenticated/_tabs/home': typeof AuthenticatedTabsHomeRoute
  '/_authenticated/_tabs/profile': typeof AuthenticatedTabsProfileRoute
  '/_authenticated/pricing/checkout-success': typeof AuthenticatedPricingCheckoutSuccessRoute
  '/_authenticated/pricing/free-trial-explanation': typeof AuthenticatedPricingFreeTrialExplanationRoute
  '/_authenticated/profile/danger-zone': typeof AuthenticatedProfileDangerZoneRoute
  '/_authenticated/redirect-to-check-out/$planInterval': typeof AuthenticatedRedirectToCheckOutPlanIntervalRoute
  '/login/email/sent': typeof LoginEmailSentRoute
  '/login/email/verify': typeof LoginEmailVerifyRoute
  '/_authenticated/pricing/': typeof AuthenticatedPricingIndexRoute
  '/login/email/': typeof LoginEmailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/from-landing'
    | '/admin-settings'
    | '/premium-demo'
    | '/account/removed'
    | '/login/'
    | '/dashboard'
    | '/home'
    | '/profile'
    | '/pricing/checkout-success'
    | '/pricing/free-trial-explanation'
    | '/profile/danger-zone'
    | '/redirect-to-check-out/$planInterval'
    | '/login/email/sent'
    | '/login/email/verify'
    | '/pricing/'
    | '/login/email/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/from-landing'
    | '/admin-settings'
    | '/premium-demo'
    | '/account/removed'
    | '/login'
    | '/dashboard'
    | '/home'
    | '/profile'
    | '/pricing/checkout-success'
    | '/pricing/free-trial-explanation'
    | '/profile/danger-zone'
    | '/redirect-to-check-out/$planInterval'
    | '/login/email/sent'
    | '/login/email/verify'
    | '/pricing'
    | '/login/email'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/from-landing'
    | '/_authenticated/_tabs'
    | '/_authenticated/admin-settings'
    | '/_authenticated/premium-demo'
    | '/account/removed'
    | '/login/'
    | '/_authenticated/_tabs/dashboard'
    | '/_authenticated/_tabs/home'
    | '/_authenticated/_tabs/profile'
    | '/_authenticated/pricing/checkout-success'
    | '/_authenticated/pricing/free-trial-explanation'
    | '/_authenticated/profile/danger-zone'
    | '/_authenticated/redirect-to-check-out/$planInterval'
    | '/login/email/sent'
    | '/login/email/verify'
    | '/_authenticated/pricing/'
    | '/login/email/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  FromLandingRoute: typeof FromLandingRoute
  AccountRemovedRoute: typeof AccountRemovedRoute
  LoginIndexRoute: typeof LoginIndexRoute
  LoginEmailSentRoute: typeof LoginEmailSentRoute
  LoginEmailVerifyRoute: typeof LoginEmailVerifyRoute
  LoginEmailIndexRoute: typeof LoginEmailIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/from-landing': {
      id: '/from-landing'
      path: '/from-landing'
      fullPath: '/from-landing'
      preLoaderRoute: typeof FromLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/removed': {
      id: '/account/removed'
      path: '/account/removed'
      fullPath: '/account/removed'
      preLoaderRoute: typeof AccountRemovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/premium-demo': {
      id: '/_authenticated/premium-demo'
      path: '/premium-demo'
      fullPath: '/premium-demo'
      preLoaderRoute: typeof AuthenticatedPremiumDemoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin-settings': {
      id: '/_authenticated/admin-settings'
      path: '/admin-settings'
      fullPath: '/admin-settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_tabs': {
      id: '/_authenticated/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedTabsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/login/email/': {
      id: '/login/email/'
      path: '/login/email'
      fullPath: '/login/email/'
      preLoaderRoute: typeof LoginEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pricing/': {
      id: '/_authenticated/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof AuthenticatedPricingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/login/email/verify': {
      id: '/login/email/verify'
      path: '/login/email/verify'
      fullPath: '/login/email/verify'
      preLoaderRoute: typeof LoginEmailVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/email/sent': {
      id: '/login/email/sent'
      path: '/login/email/sent'
      fullPath: '/login/email/sent'
      preLoaderRoute: typeof LoginEmailSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/redirect-to-check-out/$planInterval': {
      id: '/_authenticated/redirect-to-check-out/$planInterval'
      path: '/redirect-to-check-out/$planInterval'
      fullPath: '/redirect-to-check-out/$planInterval'
      preLoaderRoute: typeof AuthenticatedRedirectToCheckOutPlanIntervalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/danger-zone': {
      id: '/_authenticated/profile/danger-zone'
      path: '/profile/danger-zone'
      fullPath: '/profile/danger-zone'
      preLoaderRoute: typeof AuthenticatedProfileDangerZoneRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pricing/free-trial-explanation': {
      id: '/_authenticated/pricing/free-trial-explanation'
      path: '/pricing/free-trial-explanation'
      fullPath: '/pricing/free-trial-explanation'
      preLoaderRoute: typeof AuthenticatedPricingFreeTrialExplanationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pricing/checkout-success': {
      id: '/_authenticated/pricing/checkout-success'
      path: '/pricing/checkout-success'
      fullPath: '/pricing/checkout-success'
      preLoaderRoute: typeof AuthenticatedPricingCheckoutSuccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_tabs/profile': {
      id: '/_authenticated/_tabs/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedTabsProfileRouteImport
      parentRoute: typeof AuthenticatedTabsRoute
    }
    '/_authenticated/_tabs/home': {
      id: '/_authenticated/_tabs/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedTabsHomeRouteImport
      parentRoute: typeof AuthenticatedTabsRoute
    }
    '/_authenticated/_tabs/dashboard': {
      id: '/_authenticated/_tabs/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedTabsDashboardRouteImport
      parentRoute: typeof AuthenticatedTabsRoute
    }
  }
}

interface AuthenticatedTabsRouteChildren {
  AuthenticatedTabsDashboardRoute: typeof AuthenticatedTabsDashboardRoute
  AuthenticatedTabsHomeRoute: typeof AuthenticatedTabsHomeRoute
  AuthenticatedTabsProfileRoute: typeof AuthenticatedTabsProfileRoute
}

const AuthenticatedTabsRouteChildren: AuthenticatedTabsRouteChildren = {
  AuthenticatedTabsDashboardRoute: AuthenticatedTabsDashboardRoute,
  AuthenticatedTabsHomeRoute: AuthenticatedTabsHomeRoute,
  AuthenticatedTabsProfileRoute: AuthenticatedTabsProfileRoute,
}

const AuthenticatedTabsRouteWithChildren =
  AuthenticatedTabsRoute._addFileChildren(AuthenticatedTabsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedTabsRoute: typeof AuthenticatedTabsRouteWithChildren
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedPremiumDemoRoute: typeof AuthenticatedPremiumDemoRoute
  AuthenticatedPricingCheckoutSuccessRoute: typeof AuthenticatedPricingCheckoutSuccessRoute
  AuthenticatedPricingFreeTrialExplanationRoute: typeof AuthenticatedPricingFreeTrialExplanationRoute
  AuthenticatedProfileDangerZoneRoute: typeof AuthenticatedProfileDangerZoneRoute
  AuthenticatedRedirectToCheckOutPlanIntervalRoute: typeof AuthenticatedRedirectToCheckOutPlanIntervalRoute
  AuthenticatedPricingIndexRoute: typeof AuthenticatedPricingIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedTabsRoute: AuthenticatedTabsRouteWithChildren,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedPremiumDemoRoute: AuthenticatedPremiumDemoRoute,
  AuthenticatedPricingCheckoutSuccessRoute:
    AuthenticatedPricingCheckoutSuccessRoute,
  AuthenticatedPricingFreeTrialExplanationRoute:
    AuthenticatedPricingFreeTrialExplanationRoute,
  AuthenticatedProfileDangerZoneRoute: AuthenticatedProfileDangerZoneRoute,
  AuthenticatedRedirectToCheckOutPlanIntervalRoute:
    AuthenticatedRedirectToCheckOutPlanIntervalRoute,
  AuthenticatedPricingIndexRoute: AuthenticatedPricingIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  FromLandingRoute: FromLandingRoute,
  AccountRemovedRoute: AccountRemovedRoute,
  LoginIndexRoute: LoginIndexRoute,
  LoginEmailSentRoute: LoginEmailSentRoute,
  LoginEmailVerifyRoute: LoginEmailVerifyRoute,
  LoginEmailIndexRoute: LoginEmailIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
