import { VideoDataSubtitleTrack } from '@asbplayer-fork/common'
import { trackId } from '@/pages/util'

// Mapping between YouTube's native subtitle menu and the extension's published
// track list, extracted pure from the page script / VideoDataSyncController so
// the lifecycle rules (echo dedupe, slot preservation, translation synthesis)
// are testable without DOM or player mocks.
//
// Track identity across the two worlds is the (lang, asr, tlang?) triple:
// - every native track change fetches `/api/timedtext?...lang=&kind=&tlang=`,
//   so the triple can be read off the request URL;
// - on the extension side, the triple maps onto the published list via the
//   same identity the page script dedupes on (language + asr-ness), with
//   auto-translate corresponding 1:1 to the synthesized `${tlang}_from_${lang}`
//   machine-translation tracks.

export interface NativeTrackTriple {
  lang: string
  asr: boolean
  tlang?: string
}

export const triplesEqual = (a: NativeTrackTriple, b: NativeTrackTriple) =>
  a.lang === b.lang && a.asr === b.asr && (a.tlang ?? undefined) === (b.tlang ?? undefined)

// The triple carried by a timedtext request URL, or undefined when the request
// is not a native caption load. The extension's own subtitle fetches always
// carry `fmt=srv3` (set when the track list is published) while the native
// player requests json3 — filtering on that keeps the observer immune to our
// own fetches without any timing-based suppression.
export const timedtextTripleFromUrl = (url: string): NativeTrackTriple | undefined => {
  let parsed: URL
  try {
    parsed = new URL(url)
  } catch {
    return undefined
  }

  if (!parsed.pathname.endsWith('/api/timedtext')) {
    return undefined
  }

  const params = parsed.searchParams

  if (params.get('fmt') === 'srv3') {
    return undefined
  }

  const lang = params.get('lang')

  if (!lang) {
    return undefined
  }

  return {
    lang,
    asr: params.get('kind') === 'asr',
    tlang: params.get('tlang') || undefined,
  }
}

// The native-menu triple for a loaded track, or undefined for tracks that
// don't exist in YouTube's world (local files, generated Whisper transcripts,
// the Empty placeholder) — those can't be written back into the native menu.
export const tripleForTrack = (track: VideoDataSubtitleTrack | undefined): NativeTrackTriple | undefined => {
  if (track === undefined || track.extension !== 'ytsrv3' || track.localFile === true || !track.language) {
    return undefined
  }

  const asr = track.isAutoGenerated === true
  const separatorIndex = track.language.indexOf('_from_')

  if (separatorIndex > 0) {
    const tlang = track.language.slice(0, separatorIndex)
    const lang = track.language.slice(separatorIndex + '_from_'.length)

    if (!lang) {
      return undefined
    }

    return { lang, asr, tlang }
  }

  return { lang: track.language, asr }
}

export interface ResolvedNativeTrack {
  track: VideoDataSubtitleTrack
  // A synthesized machine-translation track is not in the published list yet;
  // the caller must merge it in after a successful load, or the reopened track
  // dialog cannot represent the selection (it resolves loaded tracks against
  // the published list only).
  synthesized: boolean
}

const baseTrackForTriple = (triple: NativeTrackTriple, available: VideoDataSubtitleTrack[]) =>
  available.find(
    (track) =>
      track.language === triple.lang &&
      (track.isAutoGenerated === true) === triple.asr &&
      track.localFile !== true &&
      typeof track.url === 'string'
  )

// Resolve a native-menu triple against the published track list. Auto-translate
// selections prefer an already-published `${tlang}_from_${lang}` variant (the
// asr-ness must match too — manual and ASR source tracks can share a language
// pair); otherwise the variant is synthesized from the base track, mirroring
// includeTranslationsForLanguageCodes in youtube-page.ts, so any of YouTube's
// translation targets works even if it was never remembered.
export const trackForTriple = (
  triple: NativeTrackTriple,
  available: VideoDataSubtitleTrack[]
): ResolvedNativeTrack | undefined => {
  if (triple.tlang === undefined) {
    const base = baseTrackForTriple(triple, available)
    return base === undefined ? undefined : { track: base, synthesized: false }
  }

  const translationLanguage = `${triple.tlang}_from_${triple.lang}`
  const existing = available.find(
    (track) =>
      track.language === translationLanguage &&
      (track.isAutoGenerated === true) === triple.asr &&
      track.localFile !== true
  )

  if (existing !== undefined) {
    return { track: existing, synthesized: false }
  }

  const base = baseTrackForTriple(triple, available)

  if (base === undefined) {
    return undefined
  }

  const synthesizedTrack = {
    ...base,
    language: translationLanguage,
    label: `${base.label} >> ${triple.tlang}`,
    url: `${base.url}&tlang=${encodeURIComponent(triple.tlang)}`,
  }

  return {
    track: { ...synthesizedTrack, id: trackId(synthesizedTrack) },
    synthesized: true,
  }
}

export interface NativeTrackSelectionPlan {
  // Slot-ordered tracks to sync: the native menu owns slot 1 only; slots 2/3
  // survive from what was last loaded.
  slots: VideoDataSubtitleTrack[]
  synthesizedTrack?: VideoDataSubtitleTrack
}

// Decide what to do about a native-menu track selection, or undefined to
// ignore it. Ignoring covers the echo paths — the write-back setOption and
// YouTube's CC-on restore both re-fetch the track that is already loaded or
// currently loading — plus triples that don't resolve against the list.
export const nativeTrackSelectionPlan = ({
  triple,
  availableTracks,
  loadedTracks,
  inFlightTriple,
  emptyTrack,
}: {
  triple: NativeTrackTriple
  availableTracks: VideoDataSubtitleTrack[]
  loadedTracks: VideoDataSubtitleTrack[] | undefined
  inFlightTriple: NativeTrackTriple | undefined
  emptyTrack: VideoDataSubtitleTrack
}): NativeTrackSelectionPlan | undefined => {
  if (inFlightTriple !== undefined && triplesEqual(inFlightTriple, triple)) {
    return undefined
  }

  const loadedTriple = tripleForTrack(loadedTracks?.[0])

  if (loadedTriple !== undefined && triplesEqual(loadedTriple, triple)) {
    return undefined
  }

  const resolved = trackForTriple(triple, availableTracks)

  if (resolved === undefined) {
    return undefined
  }

  return {
    slots: [resolved.track, loadedTracks?.[1] ?? emptyTrack, loadedTracks?.[2] ?? emptyTrack],
    synthesizedTrack: resolved.synthesized ? resolved.track : undefined,
  }
}
