import { describe, expect, it } from 'vitest'
import { VideoDataSubtitleTrack } from '@asbplayer-fork/common'
import {
  nativeTrackSelectionPlan,
  timedtextTripleFromUrl,
  trackForTriple,
  tripleForTrack,
  triplesEqual,
} from './native-track-selection.ts'

const empty: VideoDataSubtitleTrack = { id: '-', language: '-', url: '-', label: 'Empty', extension: 'srt' }

const track = (
  language: string,
  label: string,
  overrides: Partial<VideoDataSubtitleTrack> = {}
): VideoDataSubtitleTrack => {
  const url = `https://www.youtube.com/api/timedtext?lang=${language}&signature=g1&fmt=srv3`
  return { id: `${language}:${label}:${url}`, language, label, url, extension: 'ytsrv3', ...overrides }
}

describe('timedtextTripleFromUrl', () => {
  it('reads the (lang, asr, tlang) triple off a native caption request', () => {
    expect(
      timedtextTripleFromUrl('https://www.youtube.com/api/timedtext?v=abc&lang=ru&kind=asr&tlang=fr&fmt=json3')
    ).toEqual({ lang: 'ru', asr: true, tlang: 'fr' })
  })

  it('treats a missing kind as a manual track and a missing tlang as untranslated', () => {
    expect(timedtextTripleFromUrl('https://www.youtube.com/api/timedtext?v=abc&lang=de&fmt=json3')).toEqual({
      lang: 'de',
      asr: false,
      tlang: undefined,
    })
  })

  it("ignores the extension's own srv3 fetches", () => {
    expect(timedtextTripleFromUrl('https://www.youtube.com/api/timedtext?v=abc&lang=de&fmt=srv3&pot=x')).toBeUndefined()
  })

  it('ignores non-timedtext and unparseable URLs', () => {
    expect(timedtextTripleFromUrl('https://www.youtube.com/youtubei/v1/player?key=x')).toBeUndefined()
    expect(timedtextTripleFromUrl('not a url')).toBeUndefined()
  })

  it('ignores timedtext requests without a lang', () => {
    expect(timedtextTripleFromUrl('https://www.youtube.com/api/timedtext?v=abc&fmt=json3')).toBeUndefined()
  })
})

describe('tripleForTrack', () => {
  it('maps a plain YouTube track', () => {
    expect(tripleForTrack(track('de', 'German'))).toEqual({ lang: 'de', asr: false })
  })

  it('maps an ASR track', () => {
    expect(tripleForTrack(track('ru', 'Russian (auto-generated)', { isAutoGenerated: true }))).toEqual({
      lang: 'ru',
      asr: true,
    })
  })

  it('maps a machine-translation variant back to lang + tlang', () => {
    expect(tripleForTrack(track('fr_from_ru', 'Russian (auto-generated) >> fr', { isAutoGenerated: true }))).toEqual({
      lang: 'ru',
      asr: true,
      tlang: 'fr',
    })
  })

  it("returns undefined for tracks that don't exist in YouTube's world", () => {
    expect(tripleForTrack(empty)).toBeUndefined()
    expect(tripleForTrack(track('de', 'file.srt', { extension: 'srt', localFile: true }))).toBeUndefined()
    expect(
      tripleForTrack({ id: 'cached-whisper', language: 'whisper', url: 'cached', label: 'Generated', extension: 'srt' })
    ).toBeUndefined()
    expect(tripleForTrack(undefined)).toBeUndefined()
  })
})

describe('trackForTriple', () => {
  const manualRu = track('ru', 'Russian')
  const asrRu = track('ru', 'Russian (auto-generated)', { isAutoGenerated: true })

  it('disambiguates manual and ASR tracks sharing a language', () => {
    expect(trackForTriple({ lang: 'ru', asr: false }, [asrRu, manualRu])).toEqual({
      track: manualRu,
      synthesized: false,
    })
    expect(trackForTriple({ lang: 'ru', asr: true }, [asrRu, manualRu])).toEqual({ track: asrRu, synthesized: false })
  })

  it('returns undefined when no base track matches', () => {
    expect(trackForTriple({ lang: 'ja', asr: false }, [asrRu, manualRu])).toBeUndefined()
  })

  it('prefers a published translation variant whose asr-ness also matches', () => {
    const fromManual = track('fr_from_ru', 'Russian >> fr')
    const fromAsr = track('fr_from_ru', 'Russian (auto-generated) >> fr', { isAutoGenerated: true })
    expect(trackForTriple({ lang: 'ru', asr: true, tlang: 'fr' }, [manualRu, asrRu, fromManual, fromAsr])).toEqual({
      track: fromAsr,
      synthesized: false,
    })
  })

  it('synthesizes a translation variant that was never published', () => {
    const resolved = trackForTriple({ lang: 'ru', asr: true, tlang: 'pl' }, [manualRu, asrRu])
    expect(resolved?.synthesized).toBe(true)
    expect(resolved?.track.language).toBe('pl_from_ru')
    expect(resolved?.track.label).toBe('Russian (auto-generated) >> pl')
    expect(resolved?.track.url).toBe(`${asrRu.url}&tlang=pl`)
    expect(resolved?.track.isAutoGenerated).toBe(true)
    // The id must follow the trackId convention so later publish-generation
    // resolution (resolveSyncedTrackId) can fall back on the stable fields.
    expect(resolved?.track.id).toBe(`pl_from_ru:Russian (auto-generated) >> pl:${asrRu.url}&tlang=pl`)
  })
})

describe('nativeTrackSelectionPlan', () => {
  const manualDe = track('de', 'German')
  const asrRu = track('ru', 'Russian (auto-generated)', { isAutoGenerated: true })
  const available = [manualDe, asrRu]

  it('ignores the triple already loading (write-back echo mid-flight)', () => {
    expect(
      nativeTrackSelectionPlan({
        triple: { lang: 'de', asr: false },
        availableTracks: available,
        loadedTracks: undefined,
        inFlightTriple: { lang: 'de', asr: false },
        emptyTrack: empty,
      })
    ).toBeUndefined()
  })

  it('ignores the committed track (write-back echo / CC-on restore)', () => {
    expect(
      nativeTrackSelectionPlan({
        triple: { lang: 'ru', asr: true },
        availableTracks: available,
        loadedTracks: [asrRu, empty, empty],
        inFlightTriple: undefined,
        emptyTrack: empty,
      })
    ).toBeUndefined()
  })

  it('preserves slots 2/3 when switching slot 1', () => {
    const secondary = track('en', 'English')
    const plan = nativeTrackSelectionPlan({
      triple: { lang: 'ru', asr: true },
      availableTracks: available,
      loadedTracks: [manualDe, secondary, empty],
      inFlightTriple: undefined,
      emptyTrack: empty,
    })
    expect(plan?.slots).toEqual([asrRu, secondary, empty])
    expect(plan?.synthesizedTrack).toBeUndefined()
  })

  it('fills empty slots when nothing was recorded (e.g. a local file was loaded)', () => {
    const plan = nativeTrackSelectionPlan({
      triple: { lang: 'de', asr: false },
      availableTracks: available,
      loadedTracks: undefined,
      inFlightTriple: undefined,
      emptyTrack: empty,
    })
    expect(plan?.slots).toEqual([manualDe, empty, empty])
  })

  it('carries a novel synthesized translation for the caller to merge', () => {
    const plan = nativeTrackSelectionPlan({
      triple: { lang: 'ru', asr: true, tlang: 'pl' },
      availableTracks: available,
      loadedTracks: [asrRu, empty, empty],
      inFlightTriple: undefined,
      emptyTrack: empty,
    })
    expect(plan?.synthesizedTrack?.language).toBe('pl_from_ru')
    expect(plan?.slots[0]).toBe(plan?.synthesizedTrack)
  })

  it('ignores triples that resolve to nothing', () => {
    expect(
      nativeTrackSelectionPlan({
        triple: { lang: 'ja', asr: false },
        availableTracks: available,
        loadedTracks: undefined,
        inFlightTriple: undefined,
        emptyTrack: empty,
      })
    ).toBeUndefined()
  })
})

describe('triplesEqual', () => {
  it('treats missing and undefined tlang as equal', () => {
    expect(triplesEqual({ lang: 'de', asr: false }, { lang: 'de', asr: false, tlang: undefined })).toBe(true)
    expect(triplesEqual({ lang: 'de', asr: false }, { lang: 'de', asr: false, tlang: 'fr' })).toBe(false)
  })
})
