import { VideoDataSubtitleTrack } from '@asbplayer-fork/common'

// Resolution of "which tracks are currently loaded" back onto the track-select
// dialog, extracted pure from VideoDataSyncController so the two failure modes
// that bit us stay locked down by tests:
// - reopening the dialog must reflect the loaded tracks (not the
//   remembered-language match, which is empty with the remember toggle off);
// - track ids embed the signed timedtext URL and the page script re-publishes
//   the same logical tracks with freshly-signed URLs, so an exact-id match
//   alone goes stale across publish generations.

// Slot-ordered tracks to remember after a sync. Slice to the 3 selector
// slots — a confirm can append a synthetic machine-translation track whose id
// isn't in the track list (the persisted translationMode toggle reconstructs
// that part of the choice instead) — and pad with the Empty placeholder.
export const normalizeSyncedTracks = (
  data: VideoDataSubtitleTrack[],
  emptyTrack: VideoDataSubtitleTrack
): VideoDataSubtitleTrack[] => {
  const tracks = data.slice(0, 3)
  while (tracks.length < 3) {
    tracks.push(emptyTrack)
  }
  return tracks
}

// The current-list id for a recorded synced track. When the exact id is gone
// (a newer publish generation re-signed the URLs), fall back to the stable
// identity the page script itself dedupes on (language + asr-ness), preferring
// a label match when several qualify. Local-file tracks never resolve — they
// are not part of the page's track list.
export const resolveSyncedTrackId = (synced: VideoDataSubtitleTrack, available: VideoDataSubtitleTrack[]): string => {
  if (synced.id === '-') {
    return '-'
  }
  if (available.some((track) => track.id === synced.id)) {
    return synced.id
  }
  const candidates = available.filter(
    (track) =>
      track.language === synced.language &&
      (track.isAutoGenerated === true) === (synced.isAutoGenerated === true) &&
      track.localFile !== true
  )
  if (candidates.length === 0) {
    return '-'
  }
  return (candidates.find((track) => track.label === synced.label) ?? candidates[0]).id
}
