import { describe, expect, it } from 'vitest'
import { VideoDataSubtitleTrack } from '@asbplayer-fork/common'
import { normalizeSyncedTracks, resolveSyncedTrackId } from './synced-track-resolution.ts'

const empty: VideoDataSubtitleTrack = { id: '-', language: '-', url: '-', label: 'Empty', extension: 'srt' }

// YouTube-style track: the id embeds the (signed) URL, so a re-publish of the
// same logical track under a fresh signature produces a different id.
const track = (
  language: string,
  label: string,
  signature: string,
  overrides: Partial<VideoDataSubtitleTrack> = {}
): VideoDataSubtitleTrack => {
  const url = `https://www.youtube.com/api/timedtext?lang=${language}&signature=${signature}`
  return { id: `${language}:${label}:${url}`, language, label, url, extension: 'ytsrv3', ...overrides }
}

describe('normalizeSyncedTracks', () => {
  it('pads short confirms with the Empty placeholder', () => {
    const a = track('ru', 'Russian (auto-generated)', 'g1', { isAutoGenerated: true })
    expect(normalizeSyncedTracks([a], empty)).toEqual([a, empty, empty])
  })

  it('slices an appended machine-translation track to the 3 selector slots', () => {
    const a = track('ru', 'Russian (auto-generated)', 'g1', { isAutoGenerated: true })
    const synthetic = track('fr_from_ru', 'Russian (auto-generated) >> French', 'g1')
    const normalized = normalizeSyncedTracks([a, empty, empty, synthetic], empty)
    expect(normalized).toHaveLength(3)
    expect(normalized.map((t) => t.language)).toEqual(['ru', '-', '-'])
  })
})

describe('resolveSyncedTrackId', () => {
  it('passes the Empty slot through', () => {
    expect(resolveSyncedTrackId(empty, [track('ru', 'Russian', 'g1')])).toBe('-')
  })

  it('prefers the exact id when the same publish generation is still current', () => {
    const a = track('ru', 'Russian (auto-generated)', 'g1', { isAutoGenerated: true })
    expect(resolveSyncedTrackId(a, [a, track('en', 'English', 'g1')])).toBe(a.id)
  })

  it('resolves across publish generations: same logical track, freshly-signed URL', () => {
    // The bug that motivated this module: auto-sync recorded the gen-1 id, the
    // page's 500ms videoId-change republish then replaced the list with gen-2
    // ids (fresh signatures), and an exact-id prune emptied the selection.
    const gen1 = track('ru', 'Russian (auto-generated)', 'g1', { isAutoGenerated: true })
    const gen2 = track('ru', 'Russian (auto-generated)', 'g2', { isAutoGenerated: true })
    expect(gen2.id).not.toBe(gen1.id)
    expect(resolveSyncedTrackId(gen1, [gen2, track('en', 'English', 'g2')])).toBe(gen2.id)
  })

  it('does not resolve a manual track onto an ASR track of the same language', () => {
    const manual = track('ru', 'Russian', 'g1')
    const asr = track('ru', 'Russian (auto-generated)', 'g2', { isAutoGenerated: true })
    expect(resolveSyncedTrackId(manual, [asr])).toBe('-')
  })

  it('uses the label as a tiebreaker when several tracks share language + asr-ness', () => {
    const synced = track('en', 'English (UK)', 'g1')
    const us = track('en', 'English (US)', 'g2')
    const uk = track('en', 'English (UK)', 'g2')
    expect(resolveSyncedTrackId(synced, [us, uk])).toBe(uk.id)
  })

  it('falls back to the first language match when no label matches', () => {
    // Labels can differ across the two player-response sources for the same
    // logical track — language + asr-ness is the trusted identity.
    const synced = track('en', 'English - CC', 'g1')
    const other = track('en', 'English', 'g2')
    expect(resolveSyncedTrackId(synced, [other])).toBe(other.id)
  })

  it('never resolves onto a local-file track', () => {
    const synced = track('ru', 'Russian', 'g1')
    const localFile = track('ru', 'Russian', 'g2', { localFile: true })
    expect(resolveSyncedTrackId(synced, [localFile])).toBe('-')
  })

  it('returns Empty when the track is gone entirely', () => {
    const synced = track('ru', 'Russian', 'g1')
    expect(resolveSyncedTrackId(synced, [track('en', 'English', 'g2')])).toBe('-')
  })
})
