import { describe, expect, it } from 'vitest'
import { VideoDataSubtitleTrack } from '@asbplayer-fork/common'
import { selectVideoLanguageTrack } from './video-language-track-selection'

const track = (language: string, opts: { isAutoGenerated?: boolean; label?: string } = {}): VideoDataSubtitleTrack => ({
  id: `${language}:${opts.isAutoGenerated === true ? 'asr' : 'manual'}`,
  label: opts.label ?? language,
  language,
  url: `https://example.com/timedtext?lang=${language}`,
  extension: 'ytsrv3',
  ...(opts.isAutoGenerated !== undefined ? { isAutoGenerated: opts.isAutoGenerated } : {}),
})

describe('selectVideoLanguageTrack', () => {
  it('prefers the human track over ASR in the same language', () => {
    const human = track('de')
    const asr = track('de', { isAutoGenerated: true })
    expect(selectVideoLanguageTrack([asr, human], 'de')).toBe(human)
  })

  it('falls back to the ASR track when it is the only match', () => {
    const asr = track('de', { isAutoGenerated: true })
    expect(selectVideoLanguageTrack([track('en'), asr], 'de')).toBe(asr)
  })

  it('prefers the exact regional code within the same rank', () => {
    const pt = track('pt')
    const ptBr = track('pt-BR')
    expect(selectVideoLanguageTrack([pt, ptBr], 'pt-BR')).toBe(ptBr)
    expect(selectVideoLanguageTrack([ptBr, pt], 'pt')).toBe(pt)
  })

  it('matches on the primary subtag when no exact code exists', () => {
    const pt = track('pt')
    expect(selectVideoLanguageTrack([pt], 'pt-BR')).toBe(pt)
    const ptBr = track('pt-BR')
    expect(selectVideoLanguageTrack([ptBr], 'pt')).toBe(ptBr)
  })

  it('ranks human above a more exact ASR match', () => {
    const humanPt = track('pt')
    const asrPtBr = track('pt-BR', { isAutoGenerated: true })
    expect(selectVideoLanguageTrack([asrPtBr, humanPt], 'pt-BR')).toBe(humanPt)
  })

  it('never picks synthetic translation variants', () => {
    const variant = track('de_from_ru', { label: 'Russian (auto-generated) >> de' })
    expect(selectVideoLanguageTrack([variant], 'de')).toBeUndefined()
  })

  it('returns undefined when nothing matches or the language is unknown', () => {
    expect(selectVideoLanguageTrack([track('en'), track('fr')], 'de')).toBeUndefined()
    expect(selectVideoLanguageTrack([track('en')], undefined)).toBeUndefined()
    expect(selectVideoLanguageTrack([], 'de')).toBeUndefined()
  })
})
