import { VideoDataSubtitleTrack } from '@asbplayer-fork/common'

// Track selection for the video-language auto-sync policy (YouTube): given the
// published track list and the video's language (see
// services/youtube-audio-track.ts), pick the track to auto-load. Pure so the
// preference rules are unit-testable.

const primarySubtag = (code: string) => code.split('-')[0].toLowerCase()

// Candidate ranking within the video's language:
// 1. human over ASR — a human-authored track beats machine captions even when
//    the ASR variant matches the region more exactly;
// 2. exact code over primary-subtag match ('pt-BR' video: the 'pt-BR' track
//    beats 'pt', but 'pt' still matches when it is all there is);
// 3. published order (stable tiebreak).
// Synthetic auto-translate variants (`fr_from_ru`) are never candidates.
// Returns undefined when nothing matches — the caller loads nothing (silent
// fallback) rather than guessing a language the video is not in.
export const selectVideoLanguageTrack = (
  tracks: ReadonlyArray<VideoDataSubtitleTrack>,
  videoLanguage: string | undefined
): VideoDataSubtitleTrack | undefined => {
  if (!videoLanguage) {
    return undefined
  }

  const wanted = primarySubtag(videoLanguage)
  const candidates = tracks.filter(
    (track) => !!track.language && !track.language.includes('_from_') && primarySubtag(track.language) === wanted
  )

  if (candidates.length === 0) {
    return undefined
  }

  const score = (track: VideoDataSubtitleTrack) => {
    const human = track.isAutoGenerated !== true ? 2 : 0
    const exact = track.language!.toLowerCase() === videoLanguage.toLowerCase() ? 1 : 0
    return human + exact
  }

  return candidates.reduce((best, track) => (score(track) > score(best) ? track : best))
}
