// Pure helpers for detecting "the video's language" on YouTube — the language
// of the audio the user hears (dubs included), falling back to the original
// language. Consumed by the page script (youtube-page.ts) to publish
// `videoLanguage` with the track list; the video-language auto-sync policy in
// video-data-sync-controller picks the matching caption track. Kept free of
// DOM/player access so every branch is unit-testable.

// Minimal structural view of a published caption track — the fields the
// language resolution needs (VideoDataSubtitleTrack is a superset; its
// `language` is optional, so tracks without one are skipped here).
export interface CaptionTrackLike {
  language?: string
  isAutoGenerated?: boolean
}

// Minimal structural view of the web player response's
// `captions.playerCaptionsTracklistRenderer.audioTracks` entries.
export interface RendererAudioTrackLike {
  audioTrackId?: string
}

export interface AudioTrackXtags {
  // BCP-47 language code of the audio track ('ru' for the Russian dub).
  lang?: string
  // Audio content kind: 'original' | 'dubbed' | 'dubbed-auto' (not exhaustive —
  // undocumented surface).
  acont?: string
}

// Decodes the xtags blob embedded in the player's `getAudioTrack().id`
// (live-probed 2026-07-11: `"251;Cg8KBWFjb250EgZkdWJiZWQKCgoEbGFuZxICcnU"` →
// `{acont: 'dubbed', lang: 'ru'}`). The part after ';' is base64url-encoded
// protobuf: repeated length-delimited pairs of (key, value) strings. Returns
// undefined on any parse doubt — callers fall back to other signals.
export const parseAudioTrackXtags = (id: string | undefined): AudioTrackXtags | undefined => {
  if (!id) return undefined
  const separatorIndex = id.indexOf(';')
  if (separatorIndex === -1 || separatorIndex === id.length - 1) return undefined
  const blob = id.slice(separatorIndex + 1)

  let bytes: Uint8Array
  try {
    const base64 = blob.replace(/-/g, '+').replace(/_/g, '/')
    const binary = atob(base64)
    bytes = Uint8Array.from(binary, (c) => c.charCodeAt(0))
  } catch {
    return undefined
  }

  // Minimal protobuf walk: top-level repeated field 1 (0x0a) wraps one
  // (key: field 1, value: field 2) string pair per xtag. Single-byte lengths
  // only — keys/values are short ASCII tokens; anything longer is not the
  // shape we know, so bail.
  const readPair = (start: number, end: number): [string, string] | undefined => {
    let pos = start
    let key: string | undefined
    let value: string | undefined
    while (pos + 1 < end) {
      const tag = bytes[pos]
      const length = bytes[pos + 1]
      const contentStart = pos + 2
      if (length > 127 || contentStart + length > end) return undefined
      const content = String.fromCharCode(...bytes.slice(contentStart, contentStart + length))
      if (tag === 0x0a) key = content
      else if (tag === 0x12) value = content
      else return undefined
      pos = contentStart + length
    }
    return key !== undefined && value !== undefined ? [key, value] : undefined
  }

  const result: Record<string, string> = {}
  let pos = 0
  while (pos + 1 < bytes.length) {
    if (bytes[pos] !== 0x0a) return undefined
    const length = bytes[pos + 1]
    const contentStart = pos + 2
    if (length > 127 || contentStart + length > bytes.length) return undefined
    const pair = readPair(contentStart, contentStart + length)
    if (pair) result[pair[0]] = pair[1]
    pos = contentStart + length
  }

  if (Object.keys(result).length === 0) return undefined
  return { lang: result['lang'], acont: result['acont'] }
}

// This fork's synthetic auto-translate variants (`fr_from_ru`) are never "the
// video's language".
const isTranslationVariant = (track: CaptionTrackLike) => track.language?.includes('_from_') === true

// Resolves the language of the video, best signal first:
// 1. The audio track the player is set to (xtags lang) — dubs included; what
//    the user actually hears.
// 2. The sole ASR track's language — YouTube auto-generates captions only in
//    the original spoken language (dubs never get ASR; live-probed on a
//    25-track multi-dub video).
// 3. The default audio track's id prefix from the web player response
//    (`audioTracks[defaultAudioTrackIndex].audioTrackId`, e.g. 'en.4' —
//    YouTube labels it "<language> original").
// 4. The single human caption track, when it is the only one on offer.
// Undefined when every signal is ambiguous or absent — the caller stays
// silent rather than guessing.
export const resolveVideoLanguage = (params: {
  audioTrackXtags?: AudioTrackXtags
  tracks: ReadonlyArray<CaptionTrackLike>
  rendererAudioTracks?: ReadonlyArray<RendererAudioTrackLike>
  defaultAudioTrackIndex?: number
}): string | undefined => {
  const { audioTrackXtags, tracks, rendererAudioTracks, defaultAudioTrackIndex } = params

  if (audioTrackXtags?.lang) {
    return audioTrackXtags.lang
  }

  const baseTracks = tracks.filter(
    (track): track is CaptionTrackLike & { language: string } => !!track.language && !isTranslationVariant(track)
  )

  const asrLanguages = [...new Set(baseTracks.filter((t) => t.isAutoGenerated === true).map((t) => t.language))]
  if (asrLanguages.length === 1) {
    return asrLanguages[0]
  }

  if (rendererAudioTracks && defaultAudioTrackIndex !== undefined) {
    const audioTrackId = rendererAudioTracks[defaultAudioTrackIndex]?.audioTrackId
    const language = audioTrackId?.split('.')[0]
    if (language) {
      return language
    }
  }

  const humanLanguages = [...new Set(baseTracks.filter((t) => t.isAutoGenerated !== true).map((t) => t.language))]
  if (humanLanguages.length === 1 && asrLanguages.length === 0) {
    return humanLanguages[0]
  }

  return undefined
}
