import { describe, expect, it } from 'vitest'
import { parseAudioTrackXtags, resolveVideoLanguage, CaptionTrackLike } from './youtube-audio-track'

// Builds the xtags protobuf blob for given (key, value) pairs — same shape the
// player embeds in getAudioTrack().id after the ';'.
const xtagsBlob = (pairs: Array<[string, string]>): string => {
  const bytes: number[] = []
  for (const [key, value] of pairs) {
    const inner = [0x0a, key.length, ...[...key].map((c) => c.charCodeAt(0)), 0x12, value.length]
    inner.push(...[...value].map((c) => c.charCodeAt(0)))
    bytes.push(0x0a, inner.length, ...inner)
  }
  return btoa(String.fromCharCode(...bytes))
}

const track = (language: string, isAutoGenerated?: boolean): CaptionTrackLike => ({ language, isAutoGenerated })

describe('parseAudioTrackXtags', () => {
  it('decodes the live-probed Russian-dub id', () => {
    // Captured from #movie_player.getAudioTrack().id on a multi-dub video
    // (2026-07-11) while the player was set to the Russian dub.
    expect(parseAudioTrackXtags('251;Cg8KBWFjb250EgZkdWJiZWQKCgoEbGFuZxICcnU')).toEqual({
      acont: 'dubbed',
      lang: 'ru',
    })
  })

  it('decodes an original-audio blob', () => {
    const id = `140;${xtagsBlob([
      ['acont', 'original'],
      ['lang', 'en'],
    ])}`
    expect(parseAudioTrackXtags(id)).toEqual({ acont: 'original', lang: 'en' })
  })

  it('handles a lang-only blob', () => {
    expect(parseAudioTrackXtags(`251;${xtagsBlob([['lang', 'pt-BR']])}`)).toEqual({ acont: undefined, lang: 'pt-BR' })
  })

  it('returns undefined for ids without an xtags part', () => {
    expect(parseAudioTrackXtags('251')).toBeUndefined()
    expect(parseAudioTrackXtags('251;')).toBeUndefined()
    expect(parseAudioTrackXtags(undefined)).toBeUndefined()
    expect(parseAudioTrackXtags('')).toBeUndefined()
  })

  it('returns undefined for garbage payloads', () => {
    expect(parseAudioTrackXtags('251;!!!not-base64!!!')).toBeUndefined()
    expect(parseAudioTrackXtags(`251;${btoa('random text, wrong shape')}`)).toBeUndefined()
  })
})

describe('resolveVideoLanguage', () => {
  it('prefers the playing audio track (dub scenario)', () => {
    // MrBeast-style multi-dub video: English original (sole ASR) but the
    // player is set to the Russian dub — subs should match the audio heard.
    expect(
      resolveVideoLanguage({
        audioTrackXtags: { lang: 'ru', acont: 'dubbed' },
        tracks: [track('en'), track('en', true), track('ru'), track('fr')],
      })
    ).toBe('ru')
  })

  it('falls back to the sole ASR track language', () => {
    expect(
      resolveVideoLanguage({
        tracks: [track('de', true)],
      })
    ).toBe('de')
    expect(
      resolveVideoLanguage({
        audioTrackXtags: { acont: 'original' }, // no lang decoded
        tracks: [track('en'), track('ru'), track('en', true)],
      })
    ).toBe('en')
  })

  it('is not fooled by multiple ASR languages', () => {
    expect(
      resolveVideoLanguage({
        tracks: [track('en', true), track('es', true)],
      })
    ).toBeUndefined()
  })

  it('falls back to the default audio track id prefix', () => {
    expect(
      resolveVideoLanguage({
        tracks: [track('en'), track('ru')],
        rendererAudioTracks: [{ audioTrackId: 'ru.3' }, { audioTrackId: 'en.4' }],
        defaultAudioTrackIndex: 1,
      })
    ).toBe('en')
  })

  it('falls back to a single human track', () => {
    expect(resolveVideoLanguage({ tracks: [track('ja')] })).toBe('ja')
  })

  it('stays silent when human tracks are ambiguous', () => {
    expect(resolveVideoLanguage({ tracks: [track('ja'), track('en')] })).toBeUndefined()
    expect(resolveVideoLanguage({ tracks: [] })).toBeUndefined()
  })

  it('ignores synthetic translation variants everywhere', () => {
    expect(
      resolveVideoLanguage({
        tracks: [track('de_from_ru'), track('ru', true), track('de_from_ru', true)],
      })
    ).toBe('ru')
  })
})
