import {
  getEnvironmentName,
  isDevelopment,
  isDevelopmentTunnel,
  isDevelopmentWithoutThirdParties,
  isDevelopmentWithoutThirdPartiesTunnel,
  isProduction,
  isTest,
} from '../utils/environment-utils'
import { FEATURES } from '@template-app/core/features'
import { parseEmails } from './environment-config-utils'
import { EnvironmentConfig } from './environment-config-schema'

const productionConfig: EnvironmentConfig = {
  environmentName: 'production',
  // Railway injects PORT env var, fallback to 4004 for other deployments
  port: parseInt(process.env.PORT || '4004', 10),
  webUrl: 'https://app.app-monorepo-template.dev',
  shouldLogRequests: false,
  allowedCorsOrigins: [
    'https://app-monorepo-template.dev',
    'https://www.app-monorepo-template.dev',
    'https://app.app-monorepo-template.dev',
    /https:\/\/.*-template-organization\.vercel\.app(\/.*)?/, // Vercel Preview URLs
    /https:\/\/.*\.up\.railway\.app(\/.*)?/, // Railway Preview URLs
  ],
  resendApiKey: process.env.RESEND_API_KEY || '',
  stripeSecretKey: FEATURES.STRIPE ? process.env.STRIPE_SECRET_KEY || '' : '',
  stripeWebhookSecret: FEATURES.STRIPE ? process.env.STRIPE_WEBHOOK_SECRET || '' : '',
  stripeMonthlyPriceInEurId: FEATURES.STRIPE ? process.env.STRIPE_MONTHLY_PRICE_IN_EUR_ID || '' : '',
  stripeYearlyPriceInEurId: FEATURES.STRIPE ? process.env.STRIPE_YEARLY_PRICE_IN_EUR_ID || '' : '',
  sentry: FEATURES.SENTRY
    ? {
        dsn: process.env.SENTRY_DSN || '',
        options: {
          maxValueLength: 8192,
          tracesSampleRate: 1.0,
          profilesSampleRate: 1.0,
          tracePropagationTargets: ['https://app.app-monorepo-template.dev', 'https://api.app-monorepo-template.dev'],
        },
      }
    : {
        dsn: '',
        options: { maxValueLength: 8192, tracesSampleRate: 0, profilesSampleRate: 0, tracePropagationTargets: [] },
      },
  supabaseJwksUri: process.env.SUPABASE_JWKS_URI || '',
  supabaseConnectionString: process.env.SUPABASE_CONNECTION_STRING || '',
  supabaseProjectUrl: process.env.SUPABASE_PROJECT_URL || '',
  supabaseSecretKey: process.env.SUPABASE_SECRET_KEY || '',
  revenuecatApiKey: FEATURES.REVENUECAT ? process.env.REVENUECAT_API_KEY || '' : '',
  revenuecatProjectId: FEATURES.REVENUECAT ? process.env.REVENUECAT_PROJECT_ID || '' : '',
  revenuecatWebhookAuthHeader: FEATURES.REVENUECAT ? process.env.REVENUECAT_WEBHOOK_AUTH_HEADER || '' : '',
  posthogApiKey: FEATURES.POSTHOG ? process.env.POSTHOG_API_KEY || '' : '',
  shouldRateLimit: true,
  shouldMockThirdParties: false,
  shouldSlowDownApiRoutes: false,
  usersWithFreeAccess: parseEmails(process.env.USERS_WITH_FREE_ACCESS || '').validEmails,
  emailsOfTestUsers: parseEmails(process.env.EMAILS_OF_TEST_USERS || '').validEmails,
  featureFlags: {
    isCreditCardRequiredForAll: () => true,
    shouldAppBeFreeForEveryone: () => false,
  },
}

const developmentConfig: EnvironmentConfig = {
  environmentName: 'development',
  port: 4003,
  webUrl: 'http://localhost:5174',
  shouldLogRequests: true,
  allowedCorsOrigins: [
    'http://localhost:5174',
    'http://localhost:4173', // "yarn preview" origin
  ],
  resendApiKey: process.env.RESEND_API_KEY || '',
  stripeSecretKey: FEATURES.STRIPE ? process.env.STRIPE_SECRET_KEY || '' : '',
  stripeWebhookSecret: FEATURES.STRIPE ? process.env.STRIPE_WEBHOOK_SECRET || '' : '',
  stripeMonthlyPriceInEurId: FEATURES.STRIPE ? process.env.STRIPE_MONTHLY_PRICE_IN_EUR_ID || '' : '',
  stripeYearlyPriceInEurId: FEATURES.STRIPE ? process.env.STRIPE_YEARLY_PRICE_IN_EUR_ID || '' : '',
  sentry: FEATURES.SENTRY
    ? {
        dsn: process.env.SENTRY_DSN || '',
        options: {
          maxValueLength: 8192,
          tracesSampleRate: 1.0,
          profilesSampleRate: 0,
          tracePropagationTargets: ['http://localhost:5174', 'http://localhost:4003'],
        },
      }
    : {
        dsn: '',
        options: { maxValueLength: 8192, tracesSampleRate: 0, profilesSampleRate: 0, tracePropagationTargets: [] },
      },
  // Local development uses JWKS endpoint from local Supabase (supabase-dev)
  // This provides production parity - asymmetric JWT verification
  supabaseJwksUri: 'http://127.0.0.1:54321/auth/v1/.well-known/jwks.json',
  supabaseConnectionString: 'postgresql://postgres:postgres@127.0.0.1:54322/postgres',
  // shown by `yarn db:dev` command
  supabaseProjectUrl: 'http://127.0.0.1:54321',
  // Secret API key generated by Supabase with signing keys (stable, tied to signing_key.json)
  supabaseSecretKey: 'sb_secret_N7UND0UgjKTVK-Uodkm0Hg_xSvEMPvz',
  revenuecatApiKey: FEATURES.REVENUECAT ? process.env.REVENUECAT_API_KEY || '' : '',
  revenuecatProjectId: FEATURES.REVENUECAT ? process.env.REVENUECAT_PROJECT_ID || '' : '',
  revenuecatWebhookAuthHeader: FEATURES.REVENUECAT ? process.env.REVENUECAT_WEBHOOK_AUTH_HEADER || '' : '',
  posthogApiKey: FEATURES.POSTHOG ? process.env.POSTHOG_API_KEY || '' : '',
  shouldRateLimit: true,
  shouldMockThirdParties: false,
  shouldSlowDownApiRoutes: false,
  usersWithFreeAccess: parseEmails(process.env.USERS_WITH_FREE_ACCESS || '').validEmails,
  emailsOfTestUsers: parseEmails(process.env.EMAILS_OF_TEST_USERS || '').validEmails,
  featureFlags: {
    isCreditCardRequiredForAll: () => true,
    shouldAppBeFreeForEveryone: () => false,
  },
}

const developmentTunnelConfig: EnvironmentConfig = {
  ...developmentConfig,
  port: 4002,
  webUrl: process.env.WEB_URL || '',
  allowedCorsOrigins: [process.env.WEB_URL || ''],
  // Uses JWKS endpoint from local Supabase (supabase-dev-tunnel)
  supabaseJwksUri: 'http://127.0.0.1:34321/auth/v1/.well-known/jwks.json',
  supabaseConnectionString: 'postgresql://postgres:postgres@127.0.0.1:34322/postgres',
  // shown by `yarn db:dev:tunnel` command
  supabaseProjectUrl: 'http://127.0.0.1:34321',
  // Secret API key generated by Supabase with signing keys (stable, tied to signing_key.json)
  supabaseSecretKey: 'sb_secret_N7UND0UgjKTVK-Uodkm0Hg_xSvEMPvz',
}

const developmentWithoutThirdPartiesConfig: EnvironmentConfig = {
  ...developmentConfig,
  sentry: {
    dsn: 'dummySentryDsn',
    options: {
      maxValueLength: 8192,
      tracesSampleRate: 0,
      profilesSampleRate: 0,
      tracePropagationTargets: [],
    },
  },
  shouldMockThirdParties: true,
  shouldSlowDownApiRoutes: false,
}

const developmentWithoutThirdPartiesTunnelConfig: EnvironmentConfig = {
  ...developmentWithoutThirdPartiesConfig,
  webUrl: process.env.WEB_URL || '',
  allowedCorsOrigins: [process.env.WEB_URL || ''],
  supabaseConnectionString: 'postgresql://postgres:postgres@127.0.0.1:34322/postgres',
}

const testConfig: EnvironmentConfig = {
  environmentName: 'test',
  port: 1,
  webUrl: 'some-web-url',
  shouldLogRequests: false,
  allowedCorsOrigins: ['some-web-url'],
  resendApiKey: 'dummyResendApiKey',
  stripeSecretKey: FEATURES.STRIPE ? 'dummyStripeSecretKey' : '',
  stripeWebhookSecret: FEATURES.STRIPE ? 'dummyStripeWebhookSecret' : '',
  stripeMonthlyPriceInEurId: FEATURES.STRIPE ? 'dummyStripeMonthlyPriceInEurId' : '',
  stripeYearlyPriceInEurId: FEATURES.STRIPE ? 'dummyStripeYearlyPriceInEurId' : '',
  sentry: {
    // we can't pass 'dummySentryDsn' here, sentry doesn't accept that
    // this was necessary for GRAM-1788
    dsn: '',
    options: {
      maxValueLength: 8192,
      tracesSampleRate: 0,
      profilesSampleRate: 0,
      tracePropagationTargets: [],
    },
  },
  // Tests use JWKS endpoint from local Supabase (supabase-test)
  // shown by `yarn db:test` command
  supabaseJwksUri: 'http://127.0.0.1:64321/auth/v1/.well-known/jwks.json',
  supabaseConnectionString: 'postgresql://postgres:postgres@127.0.0.1:64322/postgres',
  // shown by `yarn db:test` command
  supabaseProjectUrl: 'http://127.0.0.1:64321',
  // Secret API key generated by Supabase with signing keys (stable, tied to signing_key.json)
  supabaseSecretKey: 'sb_secret_N7UND0UgjKTVK-Uodkm0Hg_xSvEMPvz',
  revenuecatApiKey: FEATURES.REVENUECAT ? 'dummyRevenuecatApiKey' : '',
  revenuecatProjectId: FEATURES.REVENUECAT ? 'dummyRevenuecatProjectId' : '',
  revenuecatWebhookAuthHeader: FEATURES.REVENUECAT ? 'dummyRevenuecatWebhookAuthHeader' : '',
  posthogApiKey: FEATURES.POSTHOG ? 'dummyPosthogApiKey' : '',
  shouldRateLimit: false,
  shouldMockThirdParties: true,
  shouldSlowDownApiRoutes: false,
  usersWithFreeAccess: [],
  emailsOfTestUsers: [],
  featureFlags: {
    isCreditCardRequiredForAll: () => true,
    shouldAppBeFreeForEveryone: () => false,
  },
}

let environmentConfig: EnvironmentConfig
export const getConfig = (): EnvironmentConfig => {
  if (!environmentConfig) {
    if (isProduction()) {
      environmentConfig = productionConfig
    } else if (isDevelopment()) {
      environmentConfig = developmentConfig
    } else if (isDevelopmentTunnel()) {
      environmentConfig = developmentTunnelConfig
    } else if (isDevelopmentWithoutThirdParties()) {
      environmentConfig = developmentWithoutThirdPartiesConfig
    } else if (isDevelopmentWithoutThirdPartiesTunnel()) {
      environmentConfig = developmentWithoutThirdPartiesTunnelConfig
    } else if (isTest()) {
      environmentConfig = testConfig
    } else {
      throw Error(`There is no config for environment: ${getEnvironmentName()}`)
    }
  }
  return environmentConfig
}
