import { VideoData, VideoDataSubtitleTrack } from '@asbplayer-fork/common'
import { trackFromDef, trackId } from '@/pages/util'
import { decodePoToken, fetchPlayerContextForPage } from '@/services/youtube'

// Minimal structural view of YouTube's untyped page-realm caption-track objects
// (shared by the ANDROID InnerTube payload and the web player response).
interface YtCaptionTrack {
  baseUrl: string
  languageCode: string
  kind?: string
  name?: { text?: string; simpleText?: string; runs?: { text?: string }[] }
}

interface YtPlayerResponse {
  videoDetails?: { videoId?: string; title?: string }
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: YtCaptionTrack[]
      translationLanguages?: unknown
    }
  }
}

declare global {
  interface Window {
    ytcfg: { get?: (key: string) => string | undefined } | undefined
    ytInitialPlayerResponse: YtPlayerResponse | undefined
  }
}

const inferVideoId = () => {
  const pathname = window.location.pathname

  if (pathname) {
    const pathVideoId = /\/(shorts|embed)\/(.*)/.exec(pathname)?.[2]

    if (pathVideoId) {
      return pathVideoId
    }
  }

  const params = new URLSearchParams(window.location.search)
  return params.get('v') ?? undefined
}

const ytTrackToSubtitleTrack = (track: YtCaptionTrack, url: URL) => {
  url.searchParams.set('fmt', 'srv3')
  const def = {
    label: track.name?.text || track.name?.simpleText || track.name?.runs?.[0]?.text || track.languageCode,
    language: track.languageCode,
    url: url.toString(),
    extension: 'ytsrv3',
    isAutoGenerated: track.kind === 'asr',
  }
  return trackFromDef(def)
}

// Language codes YouTube's translation service accepts for this video — feeds
// the translation dropdown in the track-select dialog.
const ytTranslationLanguageCodes = (captionsRenderer: { translationLanguages?: unknown } | undefined): string[] => {
  const languages = captionsRenderer?.translationLanguages
  if (!Array.isArray(languages)) {
    return []
  }
  return languages
    .map((l) => (l as { languageCode?: unknown } | null)?.languageCode)
    .filter((code): code is string => typeof code === 'string')
}

const androidInnerTubeTracks = async (videoId: string) => {
  if (typeof window.ytcfg?.get !== 'function') {
    return undefined
  }

  const apiKey = window.ytcfg.get('INNERTUBE_API_KEY')

  if (!apiKey) {
    return undefined
  }

  const response = await fetch(`https://${window.location.host}/youtubei/v1/player?key=${apiKey}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      context: {
        client: {
          clientName: 'ANDROID',
          clientVersion: '20.10.38',
          hl: window.ytcfg.get('HL') || 'en',
        },
      },
      videoId,
    }),
  })

  if (response.status !== 200) {
    return undefined
  }

  const payload = await response.json()
  const basename = payload.videoDetails?.title

  if (typeof payload?.captions?.playerCaptionsTracklistRenderer?.captionTracks !== 'object') {
    return { basename }
  }

  const tracks: YtCaptionTrack[] = payload.captions.playerCaptionsTracklistRenderer.captionTracks
  const subtitles: VideoDataSubtitleTrack[] = tracks.map((t) => {
    const url = new URL(t.baseUrl)
    return ytTrackToSubtitleTrack(t, url)
  })
  const translationLanguages = ytTranslationLanguageCodes(payload.captions.playerCaptionsTracklistRenderer)
  return { basename, subtitles, translationLanguages }
}

// The web-client player response for the current video: the page global when
// it's fresh (zero cost — this script runs in the page realm), else the
// watch-page re-fetch (the global can lag SPA navigations).
const pagePlayerResponse = async (videoId: string): Promise<YtPlayerResponse | undefined> => {
  const inline = window.ytInitialPlayerResponse
  if (inline?.videoDetails?.videoId === videoId) {
    return inline
  }
  return await fetchPlayerContextForPage()
}

// Tracks + translation languages from the page's own (web-client) player
// response. Track URLs from this source need a POT token to fetch; without one
// only the metadata (basename, translationLanguages) is usable.
const timedTextTracksFromPageContext = async (videoId: string) => {
  const pot = decodePoToken(videoId)
  const playerContext = await pagePlayerResponse(videoId)
  const renderer = playerContext?.captions?.playerCaptionsTracklistRenderer
  const tracks = renderer?.captionTracks || []
  const subtitles: VideoDataSubtitleTrack[] | undefined = pot
    ? tracks.map((track: YtCaptionTrack) => {
        const baseUrl = track.baseUrl as string
        const baseUrlWithHost = baseUrl.startsWith('/') ? `https://${window.location.host}${baseUrl}` : baseUrl
        const url = new URL(baseUrlWithHost)
        url.searchParams.set('pot', pot.poToken)
        url.searchParams.set('c', 'WEB')
        return ytTrackToSubtitleTrack(track, url)
      })
    : undefined
  const basename = playerContext?.videoDetails?.title
  const translationLanguages = ytTranslationLanguageCodes(renderer)
  return { basename, subtitles, translationLanguages }
}

// Tracks are deduplicated on (language, asr-ness) when merging the two player
// responses — label/url differ between clients for the same track.
const trackMergeKey = (track: VideoDataSubtitleTrack) =>
  `${track.language}:${track.isAutoGenerated === true ? 'asr' : 'manual'}`

const includeTranslationsForLanguageCodes = async (tracks: VideoDataSubtitleTrack[], languageCodes: string[]) => {
  const tracksIncludingTranslations: VideoDataSubtitleTrack[] = []

  for (const track of tracks) {
    tracksIncludingTranslations.push(track)

    for (const languageCode of languageCodes) {
      if (track.language !== languageCode) {
        const translationUrl = `${track.url}&tlang=${encodeURIComponent(languageCode)}`
        const newTrack = {
          ...track,
          language: `${languageCode}_from_${track.language}`,
          label: `${track.label} >> ${languageCode}`,
          url: translationUrl,
        }
        tracksIncludingTranslations.push({
          ...newTrack,
          id: trackId(newTrack),
        })
      }
    }
  }

  return tracksIncludingTranslations
}

// --- Native caption control ---
// Implements the extension's native-captions protocol (see
// NativeCaptionsController): while bound, YouTube's own CC button (and the `c`
// shortcut) is the user-facing subtitle toggle. The page observes the button,
// publishes its state to the content script, applies requested toggles through
// the player API, and hides YouTube's own caption rendering so only the
// extension overlay draws. The #movie_player API (isSubtitlesOn /
// toggleSubtitles) is unofficial but mirrors the documented iframe player API.

interface YtMoviePlayerElement extends HTMLElement {
  isSubtitlesOn?: () => boolean
  toggleSubtitles?: () => void
}

const moviePlayer = () => (document.getElementById('movie_player') ?? undefined) as YtMoviePlayerElement | undefined

const nativeCaptionsButton = () => moviePlayer()?.querySelector<HTMLElement>('.ytp-subtitles-button') ?? undefined

interface NativeCaptionsState {
  available: boolean
  on: boolean
}

// A usable control means: player API present, and the CC button rendered,
// visible, and not disabled — YouTube hides/disables it on videos without
// caption tracks, in which case the extension keeps its own toggle button.
const currentNativeCaptionsState = (): NativeCaptionsState => {
  try {
    const player = moviePlayer()
    const button = nativeCaptionsButton()

    if (
      !player ||
      typeof player.isSubtitlesOn !== 'function' ||
      typeof player.toggleSubtitles !== 'function' ||
      !button ||
      button.offsetParent === null ||
      button.getAttribute('aria-disabled') === 'true'
    ) {
      return { available: false, on: false }
    }

    return { available: true, on: player.isSubtitlesOn() === true }
  } catch (error) {
    console.error(error)
    return { available: false, on: false }
  }
}

const publishCurrentTracks = async ({
  targetTranslationLanguageCodes,
}: {
  targetTranslationLanguageCodes: string[]
}) => {
  const response: VideoData = { error: '', basename: '', subtitles: [] }
  let videoId: string | undefined

  try {
    videoId = inferVideoId()

    if (!videoId) {
      response.error = 'Could not determine video ID'
      return
    }

    let basename: string = ''
    let subtitles: VideoDataSubtitleTrack[] | undefined
    let translationLanguages: string[] | undefined

    const androidInnerTubeInfo = await androidInnerTubeTracks(videoId)

    if (androidInnerTubeInfo) {
      basename = androidInnerTubeInfo.basename
      subtitles = androidInnerTubeInfo.subtitles
      translationLanguages = androidInnerTubeInfo.translationLanguages
    }

    // The ANDROID payload is the preferred URL source (its timedtext fetches
    // don't need a POT token) but is unreliable as metadata: it ALWAYS trims
    // translationLanguages (measured: 18 vs the web response's 156, and as few
    // as 1 in some experiment buckets) and can omit human-authored caption
    // tracks. Consult the page's own player response whenever the ANDROID data
    // looks deficient — usually free, since the page global is read in-realm.
    const androidLooksComplete =
      subtitles !== undefined &&
      !!basename &&
      (translationLanguages?.length ?? 0) >= 50 &&
      subtitles.some((track) => track.isAutoGenerated !== true)

    if (!androidLooksComplete) {
      try {
        const pageInfo = await timedTextTracksFromPageContext(videoId)
        basename = basename || pageInfo.basename || ''

        if (subtitles === undefined) {
          subtitles = pageInfo.subtitles
        } else if (pageInfo.subtitles !== undefined) {
          // Merge in tracks the ANDROID payload omitted (typically the
          // human-authored ones).
          const covered = new Set(subtitles.map(trackMergeKey))
          subtitles = [
            ...subtitles,
            ...pageInfo.subtitles.filter((track: VideoDataSubtitleTrack) => !covered.has(trackMergeKey(track))),
          ]
        }

        if (pageInfo.translationLanguages.length > (translationLanguages?.length ?? 0)) {
          translationLanguages = pageInfo.translationLanguages
        }
      } catch (error) {
        // The ANDROID data (if any) is still usable on its own.
        console.error(error)
      }
    }

    if (subtitles !== undefined) {
      subtitles = await includeTranslationsForLanguageCodes(subtitles, targetTranslationLanguageCodes)
    }

    response.basename = basename || document.title
    response.subtitles = subtitles ?? []
    response.translationLanguages = translationLanguages ?? []
    return videoId
  } catch (error) {
    console.error(error)
    if (error instanceof Error) {
      response.error = error.message
    } else {
      response.error = String(error)
    }
  } finally {
    // Do not publish subs if the video ID changed during track extraction - e.g. likely to happen on Shorts
    if (videoId === inferVideoId()) {
      document.dispatchEvent(
        new CustomEvent('asbplayer-synced-data', {
          detail: response,
        })
      )
    }
  }
}

export default defineUnlistedScript(() => {
  let lastVideoIdDispatched: string | undefined
  // The extension reads the target languages from settings and sends them with
  // each request; the page realm can't read settings itself, so the interval
  // republish below reuses the last requested codes. Publishing without them
  // would drop the `>> code` variants and break remembered-track auto-sync on
  // SPA navigations.
  let lastTargetTranslationLanguageCodes: string[] = []

  document.addEventListener(
    'asbplayer-get-synced-data',
    async (e) => {
      const targetTranslationLanguageCodes: string[] =
        ((e as CustomEvent).detail?.targetTranslationLanguageCodes as string[] | undefined) ?? []
      lastTargetTranslationLanguageCodes = targetTranslationLanguageCodes
      lastVideoIdDispatched = await publishCurrentTracks({ targetTranslationLanguageCodes })
    },
    false
  )

  // --- Native caption control wiring ---

  let captionControlBound = false
  let observedCaptionsButton: HTMLElement | undefined
  let lastPublishedCaptionsState: NativeCaptionsState | undefined
  let captionsSuppressionStyle: HTMLStyleElement | undefined

  const publishNativeCaptionsState = (force = false) => {
    const state = currentNativeCaptionsState()

    if (
      !force &&
      lastPublishedCaptionsState !== undefined &&
      lastPublishedCaptionsState.available === state.available &&
      lastPublishedCaptionsState.on === state.on
    ) {
      return
    }

    lastPublishedCaptionsState = state
    document.dispatchEvent(new CustomEvent('asbplayer-native-captions-state', { detail: state }))
  }

  const captionsButtonObserver = new MutationObserver(() => publishNativeCaptionsState())

  // (Re-)attach the observer to the current CC button node — YouTube can
  // replace player chrome across SPA navigations, which silently kills an
  // observer on the old node. Cheap, so re-checked from the interval below.
  const ensureCaptionsButtonObserver = () => {
    const button = nativeCaptionsButton()

    if (button === observedCaptionsButton) {
      return
    }

    captionsButtonObserver.disconnect()
    observedCaptionsButton = button

    if (button) {
      captionsButtonObserver.observe(button, {
        attributes: true,
        attributeFilter: ['aria-pressed', 'aria-disabled', 'style', 'class'],
      })
    }

    publishNativeCaptionsState()
  }

  // While the extension renders the subtitles, YouTube's own caption window
  // would double-display underneath: the native CC state stays "on" (it is the
  // user-facing toggle) but its rendering is hidden.
  const suppressNativeCaptionsRendering = (suppress: boolean) => {
    if (suppress) {
      if (!captionsSuppressionStyle) {
        captionsSuppressionStyle = document.createElement('style')
        captionsSuppressionStyle.textContent = '.ytp-caption-window-container { display: none !important; }'
      }

      if (!captionsSuppressionStyle.isConnected) {
        ;(document.head || document.documentElement).appendChild(captionsSuppressionStyle)
      }
    } else {
      captionsSuppressionStyle?.remove()
    }
  }

  document.addEventListener('asbplayer-native-captions-bind', () => {
    captionControlBound = true
    suppressNativeCaptionsRendering(true)
    ensureCaptionsButtonObserver()
    publishNativeCaptionsState(true)
  })

  document.addEventListener('asbplayer-native-captions-unbind', () => {
    captionControlBound = false
    suppressNativeCaptionsRendering(false)
  })

  document.addEventListener('asbplayer-native-captions-set', (e) => {
    const on = (e as CustomEvent).detail === true

    try {
      const player = moviePlayer()

      if (player?.isSubtitlesOn && player.toggleSubtitles && player.isSubtitlesOn() !== on) {
        player.toggleSubtitles()
      }
    } catch (error) {
      console.error(error)
    }

    publishNativeCaptionsState()
  })

  let publishing = false

  // Handle YT shorts: Publish subtitle tracks according to current video ID
  setInterval(async () => {
    if (captionControlBound) {
      // Backstop for changes the attribute observer can't see: button node
      // replacement and availability flips on SPA navigation.
      ensureCaptionsButtonObserver()
      publishNativeCaptionsState()
    }

    if (publishing) {
      return
    }

    try {
      publishing = true
      const videoId = inferVideoId()
      if (lastVideoIdDispatched && videoId && lastVideoIdDispatched !== videoId) {
        lastVideoIdDispatched = await publishCurrentTracks({
          targetTranslationLanguageCodes: lastTargetTranslationLanguageCodes,
        })
      }
    } finally {
      publishing = false
    }
  }, 500)
})
