import { VideoData, VideoDataSubtitleTrack } from '@asbplayer-fork/common'
import { trackFromDef, trackId } from '@/pages/util'
import { timedtextTripleFromUrl, triplesEqual, type NativeTrackTriple } from '@/services/native-track-selection'
import { parseAudioTrackXtags, resolveVideoLanguage } from '@/services/youtube-audio-track'
import { decodePoToken, fetchPlayerContextForPage } from '@/services/youtube'

// Minimal structural view of YouTube's untyped page-realm caption-track objects
// (shared by the ANDROID InnerTube payload and the web player response).
interface YtCaptionTrack {
  baseUrl: string
  languageCode: string
  kind?: string
  name?: { text?: string; simpleText?: string; runs?: { text?: string }[] }
}

interface YtPlayerResponse {
  videoDetails?: { videoId?: string; title?: string }
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: YtCaptionTrack[]
      translationLanguages?: unknown
      // Multi-audio (dubbed) videos: one entry per audio track; the default
      // index points at the original ("<language> original").
      audioTracks?: { audioTrackId?: string }[]
      defaultAudioTrackIndex?: number
    }
  }
}

declare global {
  interface Window {
    ytcfg: { get?: (key: string) => string | undefined } | undefined
    ytInitialPlayerResponse: YtPlayerResponse | undefined
  }
}

const inferVideoId = () => {
  const pathname = window.location.pathname

  if (pathname) {
    const pathVideoId = /\/(shorts|embed)\/(.*)/.exec(pathname)?.[2]

    if (pathVideoId) {
      return pathVideoId
    }
  }

  const params = new URLSearchParams(window.location.search)
  return params.get('v') ?? undefined
}

const ytTrackToSubtitleTrack = (track: YtCaptionTrack, url: URL) => {
  url.searchParams.set('fmt', 'srv3')
  const def = {
    label: track.name?.text || track.name?.simpleText || track.name?.runs?.[0]?.text || track.languageCode,
    language: track.languageCode,
    url: url.toString(),
    extension: 'ytsrv3',
    isAutoGenerated: track.kind === 'asr',
  }
  return trackFromDef(def)
}

// Language codes YouTube's translation service accepts for this video — feeds
// the translation dropdown in the track-select dialog.
const ytTranslationLanguageCodes = (captionsRenderer: { translationLanguages?: unknown } | undefined): string[] => {
  const languages = captionsRenderer?.translationLanguages
  if (!Array.isArray(languages)) {
    return []
  }
  return languages
    .map((l) => (l as { languageCode?: unknown } | null)?.languageCode)
    .filter((code): code is string => typeof code === 'string')
}

const androidInnerTubeTracks = async (videoId: string) => {
  if (typeof window.ytcfg?.get !== 'function') {
    return undefined
  }

  const apiKey = window.ytcfg.get('INNERTUBE_API_KEY')

  if (!apiKey) {
    return undefined
  }

  const response = await fetch(`https://${window.location.host}/youtubei/v1/player?key=${apiKey}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      context: {
        client: {
          clientName: 'ANDROID',
          clientVersion: '20.10.38',
          hl: window.ytcfg.get('HL') || 'en',
        },
      },
      videoId,
    }),
  })

  if (response.status !== 200) {
    return undefined
  }

  const payload = await response.json()
  const basename = payload.videoDetails?.title

  if (typeof payload?.captions?.playerCaptionsTracklistRenderer?.captionTracks !== 'object') {
    return { basename }
  }

  const tracks: YtCaptionTrack[] = payload.captions.playerCaptionsTracklistRenderer.captionTracks
  const subtitles: VideoDataSubtitleTrack[] = tracks.map((t) => {
    const url = new URL(t.baseUrl)
    return ytTrackToSubtitleTrack(t, url)
  })
  const translationLanguages = ytTranslationLanguageCodes(payload.captions.playerCaptionsTracklistRenderer)
  return { basename, subtitles, translationLanguages }
}

// Speculative InnerTube fetch for the current video, so the network round trip
// overlaps the content script's own boot (video binding, settings reads) — by
// the time asbplayer-get-synced-data arrives the tracks are usually already in
// flight or done. ytcfg is populated by YouTube's inline boot scripts, so very
// early in a cold load arming can fail; callers retry (script startup + the
// 500 ms interval, which also re-arms on SPA navigations).
let innerTubePrefetch:
  { videoId: string; promise: Promise<Awaited<ReturnType<typeof androidInnerTubeTracks>>> } | undefined

const armInnerTubePrefetch = () => {
  const videoId = inferVideoId()

  if (videoId === undefined || innerTubePrefetch?.videoId === videoId) {
    return
  }

  if (typeof window.ytcfg?.get !== 'function' || !window.ytcfg.get('INNERTUBE_API_KEY')) {
    return
  }

  innerTubePrefetch = { videoId, promise: androidInnerTubeTracks(videoId).catch(() => undefined) }
}

// Timedtext URLs are signed with a ~6 h expiry (`expire` unix seconds,
// covered by `sparams` — an expired signature 404s). A cached player response
// can outlive that: when a long-idle tab wakes, YouTube partial-reloads the
// player for the SAME video id, the binding re-requests tracks, and both the
// InnerTube prefetch and the ytInitialPlayerResponse global still "match"
// while holding hours-old URLs. Serving those 404s the subtitle fetch and
// silently downgrades the video to native captions, so every cached source is
// checked against its own URL expiry before use. The margin covers the rest
// of the pipeline (auto-sync fetch) plus modest client-clock skew.
const URL_EXPIRY_MARGIN_MS = 60 * 1000

const timedtextUrlExpired = (url: string | string[] | undefined): boolean => {
  const urlString = Array.isArray(url) ? url[0] : url

  if (!urlString) {
    return false
  }

  try {
    // Web-response baseUrls can be host-relative.
    const expireParam = new URL(urlString, `https://${window.location.host}`).searchParams.get('expire')

    if (expireParam === null) {
      return false
    }

    const expire = Number(expireParam)
    return Number.isFinite(expire) && expire * 1000 < Date.now() + URL_EXPIRY_MARGIN_MS
  } catch {
    return false
  }
}

// The web-client player response for the current video: the page global when
// it's fresh (zero cost — this script runs in the page realm), else the
// watch-page re-fetch (the global can lag SPA navigations, and its signed
// track URLs can expire during a long idle).
const pagePlayerResponse = async (videoId: string): Promise<YtPlayerResponse | undefined> => {
  const inline = window.ytInitialPlayerResponse
  const inlineTracks = inline?.captions?.playerCaptionsTracklistRenderer?.captionTracks

  if (
    inline?.videoDetails?.videoId === videoId &&
    inlineTracks?.some((track) => timedtextUrlExpired(track.baseUrl)) !== true
  ) {
    return inline
  }

  return await fetchPlayerContextForPage()
}

// POTs harvested from observed /api/timedtext fetches, keyed by video id: the
// native caption renderer's own requests carry a token that timedtext accepts
// for this fork's srv3 fetches too (verified live 2026-07-12 — signed URL
// without a POT returns 200 with an empty body). The sessionStorage cache
// decodePoToken reads is no longer minted in every session, so harvesting is
// the primary source in practice.
const harvestedTimedtextPots = new Map<string, string>()

const harvestTimedtextPot = (resourceUrl: string) => {
  try {
    const url = new URL(resourceUrl)

    if (!url.pathname.endsWith('/api/timedtext')) {
      return
    }

    const videoId = url.searchParams.get('v')
    const pot = url.searchParams.get('pot')

    if (videoId && pot) {
      harvestedTimedtextPots.set(videoId, pot)
    }
  } catch {
    // Not a parseable URL — not a timedtext fetch.
  }
}

const knownPoToken = (videoId: string): { poToken: string } | undefined => {
  const cached = decodePoToken(videoId)

  if (cached) {
    return cached
  }

  const harvested = harvestedTimedtextPots.get(videoId)
  return harvested ? { poToken: harvested } : undefined
}

// Whether the native caption window is currently hidden (provisional or bound
// suppression) — gates the induced fetch below, which must never visibly
// flash captions. Maintained by suppressNativeCaptionsRendering.
let captionsRenderingSuppressed = false

// Force the native player to issue a timedtext fetch we can harvest the POT
// from, by flipping the CC toggle: on→(fetch)→off restore when CC was off,
// off→on refetch when CC was on but its organic fetch hasn't been observed
// yet (the captions module can lazy-load well after playback starts). Only
// while rendering is suppressed, so nothing flashes; the CC state ends where
// it started. Pre-bind the caption-state observer is not attached yet, so the
// transient flip never reaches the content script.
const induceNativeCaptionFetch = () => {
  const flipBack = (toOn: boolean, delayMs: number) => {
    setTimeout(() => {
      try {
        const player = moviePlayer()

        if (player?.isSubtitlesOn && player.toggleSubtitles && player.isSubtitlesOn() !== toOn) {
          player.toggleSubtitles()
        }
      } catch (error) {
        console.error(error)
      }
    }, delayMs)
  }

  try {
    const player = moviePlayer()

    if (!player?.isSubtitlesOn || !player.toggleSubtitles || !captionsRenderingSuppressed) {
      return
    }

    if (player.isSubtitlesOn() === true) {
      player.toggleSubtitles()
      flipBack(true, 300)
    } else {
      player.toggleSubtitles()
      flipBack(false, 1500)
    }
  } catch (error) {
    console.error(error)
  }
}

const POT_POLL_INTERVAL_MS = 500
const POT_POLL_MAX_ATTEMPTS = 16
// Poll iteration at which to induce a native fetch (~1.5s in) — gives an
// organic CC-on fetch time to land first.
const POT_INDUCE_ATTEMPT = 3

// Waits for a POT to become available from any source. Gives up early when
// the user navigates away from the video.
const waitForPoToken = async (videoId: string) => {
  for (let attempt = 0; attempt < POT_POLL_MAX_ATTEMPTS; attempt++) {
    if (attempt === POT_INDUCE_ATTEMPT) {
      induceNativeCaptionFetch()
    }

    await new Promise((resolve) => setTimeout(resolve, POT_POLL_INTERVAL_MS))

    if (inferVideoId() !== videoId) {
      return undefined
    }

    const pot = knownPoToken(videoId)

    if (pot !== undefined) {
      return pot
    }
  }

  return undefined
}

// Tracks + translation languages from the page's own (web-client) player
// response. Track URLs from this source need a POT token to fetch; without one
// only the metadata (basename, translationLanguages) is usable.
//
// waitForPot: set when this response is the only usable URL source — the
// ANDROID payload yielded no tracks, which happens on videos it is login-gated
// for (e.g. age-restricted). Publishing without the POT then would wrongly
// mark a captioned video subtitle-less, so poll for the token instead.
// Metadata-only consultations (ANDROID already supplied URLs) never wait.
const timedTextTracksFromPageContext = async (videoId: string, { waitForPot }: { waitForPot: boolean }) => {
  const playerContext = await pagePlayerResponse(videoId)
  const renderer = playerContext?.captions?.playerCaptionsTracklistRenderer
  const tracks = renderer?.captionTracks || []

  const pot = knownPoToken(videoId) ?? (waitForPot && tracks.length > 0 ? await waitForPoToken(videoId) : undefined)

  const subtitles: VideoDataSubtitleTrack[] | undefined = pot
    ? tracks.map((track: YtCaptionTrack) => {
        const baseUrl = track.baseUrl as string
        const baseUrlWithHost = baseUrl.startsWith('/') ? `https://${window.location.host}${baseUrl}` : baseUrl
        const url = new URL(baseUrlWithHost)
        url.searchParams.set('pot', pot.poToken)
        url.searchParams.set('c', 'WEB')
        return ytTrackToSubtitleTrack(track, url)
      })
    : undefined
  const basename = playerContext?.videoDetails?.title
  const translationLanguages = ytTranslationLanguageCodes(renderer)
  return { basename, subtitles, translationLanguages }
}

// Tracks are deduplicated on (language, asr-ness) when merging the two player
// responses — label/url differ between clients for the same track.
const trackMergeKey = (track: VideoDataSubtitleTrack) =>
  `${track.language}:${track.isAutoGenerated === true ? 'asr' : 'manual'}`

const includeTranslationsForLanguageCodes = async (tracks: VideoDataSubtitleTrack[], languageCodes: string[]) => {
  const tracksIncludingTranslations: VideoDataSubtitleTrack[] = []

  for (const track of tracks) {
    tracksIncludingTranslations.push(track)

    for (const languageCode of languageCodes) {
      if (track.language !== languageCode) {
        const translationUrl = `${track.url}&tlang=${encodeURIComponent(languageCode)}`
        const newTrack = {
          ...track,
          language: `${languageCode}_from_${track.language}`,
          label: `${track.label} >> ${languageCode}`,
          url: translationUrl,
        }
        tracksIncludingTranslations.push({
          ...newTrack,
          id: trackId(newTrack),
        })
      }
    }
  }

  return tracksIncludingTranslations
}

// --- Native caption control ---
// Implements the extension's native-captions protocol (see
// NativeCaptionsController): while bound, YouTube's own CC button (and the `c`
// shortcut) is the user-facing subtitle toggle. The page observes the button,
// publishes its state to the content script, applies requested toggles through
// the player API, and hides YouTube's own caption rendering so only the
// extension overlay draws. The #movie_player API (isSubtitlesOn /
// toggleSubtitles) is unofficial but mirrors the documented iframe player API.

interface YtMoviePlayerElement extends HTMLElement {
  isSubtitlesOn?: () => boolean
  toggleSubtitles?: () => void
  setOption?: (module: string, option: string, value: unknown) => void
  getOption?: (
    module: string,
    option: string
  ) => { languageCode?: string; kind?: string; translationLanguage?: { languageCode?: string } } | undefined
  // The audio track the player is set to. Its `id` embeds the xtags blob the
  // video-language detection decodes (`251;Cg8...` → acont/lang); the rest of
  // the object is obfuscated and not relied upon.
  getAudioTrack?: () => { id?: string } | undefined
}

const moviePlayer = () => (document.getElementById('movie_player') ?? undefined) as YtMoviePlayerElement | undefined

const nativeCaptionsButton = () => moviePlayer()?.querySelector<HTMLElement>('.ytp-subtitles-button') ?? undefined

interface NativeCaptionsState {
  available: boolean
  on: boolean
}

// A usable control means: player API present, and the CC button rendered,
// visible, and not disabled — YouTube hides/disables it on videos without
// caption tracks, in which case the extension keeps its own toggle button.
const currentNativeCaptionsState = (): NativeCaptionsState => {
  try {
    const player = moviePlayer()
    const button = nativeCaptionsButton()

    if (
      !player ||
      typeof player.isSubtitlesOn !== 'function' ||
      typeof player.toggleSubtitles !== 'function' ||
      !button ||
      button.offsetParent === null ||
      button.getAttribute('aria-disabled') === 'true'
    ) {
      return { available: false, on: false }
    }

    return { available: true, on: player.isSubtitlesOn() === true }
  } catch (error) {
    console.error(error)
    return { available: false, on: false }
  }
}

// The video's language for the auto-sync policy: the player's current audio
// track first (dubs included — subs should match what the user hears), then
// original-language signals. The renderer read uses ONLY the in-realm page
// global, and only while it is still for this video — re-fetching the watch
// page just for this fallback isn't worth a network round trip (the audio and
// ASR signals cover virtually every video).
const currentVideoLanguage = (videoId: string, tracks: VideoDataSubtitleTrack[]): string | undefined => {
  let audioTrackId: string | undefined
  try {
    audioTrackId = moviePlayer()?.getAudioTrack?.()?.id
  } catch (error) {
    console.error(error)
  }

  const inline = window.ytInitialPlayerResponse
  const renderer =
    inline?.videoDetails?.videoId === videoId ? inline?.captions?.playerCaptionsTracklistRenderer : undefined

  return resolveVideoLanguage({
    audioTrackXtags: parseAudioTrackXtags(audioTrackId),
    tracks,
    rendererAudioTracks: renderer?.audioTracks,
    defaultAudioTrackIndex: renderer?.defaultAudioTrackIndex,
  })
}

const publishCurrentTracks = async ({
  targetTranslationLanguageCodes,
}: {
  targetTranslationLanguageCodes: string[]
}) => {
  const response: VideoData = { error: '', basename: '', subtitles: [] }
  let videoId: string | undefined

  try {
    videoId = inferVideoId()

    if (!videoId) {
      response.error = 'Could not determine video ID'
      return
    }

    let basename: string = ''
    let subtitles: VideoDataSubtitleTrack[] | undefined
    let translationLanguages: string[] | undefined

    // A failed prefetch (resolved undefined) falls through to a direct fetch —
    // the failure may have been transient.
    let prefetched = innerTubePrefetch?.videoId === videoId ? await innerTubePrefetch.promise : undefined

    if (prefetched?.subtitles?.some((track) => timedtextUrlExpired(track.url))) {
      // Long-idle wake: the prefetch outlived its URLs' signatures. Drop the
      // cache entry too, so the interval re-arms a fresh one for this video.
      if (innerTubePrefetch?.videoId === videoId) {
        innerTubePrefetch = undefined
      }
      prefetched = undefined
    }

    const androidInnerTubeInfo = prefetched ?? (await androidInnerTubeTracks(videoId))

    if (androidInnerTubeInfo) {
      basename = androidInnerTubeInfo.basename
      subtitles = androidInnerTubeInfo.subtitles
      translationLanguages = androidInnerTubeInfo.translationLanguages
    }

    // The ANDROID payload is the preferred URL source (its timedtext fetches
    // don't need a POT token) but is unreliable as metadata: it ALWAYS trims
    // translationLanguages (measured: 18 vs the web response's 156, and as few
    // as 1 in some experiment buckets) and can omit human-authored caption
    // tracks. Consult the page's own player response whenever the ANDROID data
    // looks deficient — usually free, since the page global is read in-realm.
    const androidLooksComplete =
      subtitles !== undefined &&
      !!basename &&
      (translationLanguages?.length ?? 0) >= 50 &&
      subtitles.some((track) => track.isAutoGenerated !== true)

    if (!androidLooksComplete) {
      try {
        const pageInfo = await timedTextTracksFromPageContext(videoId, { waitForPot: subtitles === undefined })
        basename = basename || pageInfo.basename || ''

        if (subtitles === undefined) {
          subtitles = pageInfo.subtitles
        } else if (pageInfo.subtitles !== undefined) {
          // Merge in tracks the ANDROID payload omitted (typically the
          // human-authored ones).
          const covered = new Set(subtitles.map(trackMergeKey))
          subtitles = [
            ...subtitles,
            ...pageInfo.subtitles.filter((track: VideoDataSubtitleTrack) => !covered.has(trackMergeKey(track))),
          ]
        }

        if (pageInfo.translationLanguages.length > (translationLanguages?.length ?? 0)) {
          translationLanguages = pageInfo.translationLanguages
        }
      } catch (error) {
        // The ANDROID data (if any) is still usable on its own.
        console.error(error)
      }
    }

    // Resolved BEFORE the translation variants are appended, so the ASR /
    // single-human-track heuristics see only real tracks.
    response.videoLanguage = currentVideoLanguage(videoId, subtitles ?? [])

    if (subtitles !== undefined) {
      subtitles = await includeTranslationsForLanguageCodes(subtitles, targetTranslationLanguageCodes)
    }

    response.basename = basename || document.title
    response.subtitles = subtitles ?? []
    response.translationLanguages = translationLanguages ?? []
    return videoId
  } catch (error) {
    console.error(error)
    if (error instanceof Error) {
      response.error = error.message
    } else {
      response.error = String(error)
    }
  } finally {
    // Do not publish subs if the video ID changed during track extraction - e.g. likely to happen on Shorts
    if (videoId === inferVideoId()) {
      document.dispatchEvent(
        new CustomEvent('asbplayer-synced-data', {
          detail: response,
        })
      )
    }
  }
}

export default defineUnlistedScript(() => {
  let lastVideoIdDispatched: string | undefined
  // The extension reads the target languages from settings and sends them with
  // each request; the page realm can't read settings itself, so the interval
  // republish below reuses the last requested codes. Publishing without them
  // would drop the `>> code` variants and break remembered-track auto-sync on
  // SPA navigations.
  let lastTargetTranslationLanguageCodes: string[] = []

  document.addEventListener(
    'asbplayer-get-synced-data',
    async (e) => {
      const targetTranslationLanguageCodes: string[] =
        ((e as CustomEvent).detail?.targetTranslationLanguageCodes as string[] | undefined) ?? []
      lastTargetTranslationLanguageCodes = targetTranslationLanguageCodes
      lastVideoIdDispatched = await publishCurrentTracks({ targetTranslationLanguageCodes })
    },
    false
  )

  // --- Native caption control wiring ---

  let captionControlBound = false
  let observedCaptionsButton: HTMLElement | undefined
  let lastPublishedCaptionsState: NativeCaptionsState | undefined
  let captionsSuppressionStyle: HTMLStyleElement | undefined
  // Native gear-menu selections are only forwarded for the video the extension
  // has actually loaded subtitles for (armed on bind/write-back). This is what
  // keeps the extension's own remembered-track auto-sync the initial source:
  // during an SPA navigation the binding from the previous video is still live,
  // and YouTube (with CC on) fetches its persisted track for the NEW video
  // before the extension has loaded anything — that fetch must not be treated
  // as a user selection.
  let armedTrackVideoId: string | undefined

  const publishNativeCaptionsState = (force = false) => {
    const state = currentNativeCaptionsState()

    if (
      !force &&
      lastPublishedCaptionsState !== undefined &&
      lastPublishedCaptionsState.available === state.available &&
      lastPublishedCaptionsState.on === state.on
    ) {
      return
    }

    const captionsTurnedOn = state.on && lastPublishedCaptionsState?.on !== true
    lastPublishedCaptionsState = state
    document.dispatchEvent(new CustomEvent('asbplayer-native-captions-state', { detail: state }))

    if (captionsTurnedOn) {
      // Deferred write-back (see requestedTrackTriple): re-assert the
      // extension's loaded track the moment captions turn on, before YouTube's
      // own persisted-track restore can win.
      applyRequestedTrack()
    }
  }

  const captionsButtonObserver = new MutationObserver(() => publishNativeCaptionsState())

  // (Re-)attach the observer to the current CC button node — YouTube can
  // replace player chrome across SPA navigations, which silently kills an
  // observer on the old node. Cheap, so re-checked from the interval below.
  const ensureCaptionsButtonObserver = () => {
    const button = nativeCaptionsButton()

    if (button === observedCaptionsButton) {
      return
    }

    captionsButtonObserver.disconnect()
    observedCaptionsButton = button

    if (button) {
      captionsButtonObserver.observe(button, {
        attributes: true,
        attributeFilter: ['aria-pressed', 'aria-disabled', 'style', 'class'],
      })
    }

    publishNativeCaptionsState()
  }

  // While the extension renders the subtitles, YouTube's own caption window
  // would double-display underneath: the native CC state stays "on" (it is the
  // user-facing toggle) but its rendering is hidden.
  const suppressNativeCaptionsRendering = (suppress: boolean) => {
    captionsRenderingSuppressed = suppress

    if (suppress) {
      if (!captionsSuppressionStyle) {
        captionsSuppressionStyle = document.createElement('style')
        captionsSuppressionStyle.textContent = '.ytp-caption-window-container { display: none !important; }'
      }

      if (!captionsSuppressionStyle.isConnected) {
        ;(document.head || document.documentElement).appendChild(captionsSuppressionStyle)
      }
    } else {
      captionsSuppressionStyle?.remove()
    }
  }

  // --- Provisional native-caption suppression ---
  // The subtitle pipeline (content-script boot → track-list fetch → srv3
  // fetch + parse) runs a second or two behind YouTube's own caption renderer,
  // so with CC on the native captions would flash before the overlay takes
  // over. On watch pages the caption window is therefore hidden as soon as a
  // video is detected — before knowing whether the extension will bind — and
  // revealed again when it turns out not to: the content script declines
  // (asbplayer-native-captions-decline, sent when auto-sync resolves to "load
  // nothing"), or the timeout fires as a safety net so an extension failure
  // can never leave native captions permanently hidden. Watch pages only:
  // Shorts/preview bindings never speak for the whole page, so a provisional
  // hide there could not be reliably released.
  const PROVISIONAL_SUPPRESSION_TIMEOUT_MS = 10000
  let provisionalVideoId: string | undefined
  let provisionalSuppressionActive = false
  let provisionalSuppressionTimeout: ReturnType<typeof setTimeout> | undefined

  // Desktop watch pages only — on m.youtube.com the native-captions takeover
  // degrades gracefully (no #movie_player on the content side), so neither
  // bind nor decline would ever release a provisional hide there.
  const watchPageVideoId = () =>
    window.location.hostname !== 'm.youtube.com' && window.location.pathname === '/watch'
      ? (new URLSearchParams(window.location.search).get('v') ?? undefined)
      : undefined

  const releaseProvisionalSuppression = () => {
    if (provisionalSuppressionTimeout !== undefined) {
      clearTimeout(provisionalSuppressionTimeout)
      provisionalSuppressionTimeout = undefined
    }

    if (!provisionalSuppressionActive) {
      return
    }

    provisionalSuppressionActive = false

    if (!captionControlBound) {
      suppressNativeCaptionsRendering(false)
    }
  }

  const applyProvisionalSuppression = () => {
    const videoId = watchPageVideoId()

    if (videoId === provisionalVideoId) {
      return
    }

    provisionalVideoId = videoId
    releaseProvisionalSuppression()

    if (videoId === undefined || captionControlBound) {
      return
    }

    provisionalSuppressionActive = true
    suppressNativeCaptionsRendering(true)
    provisionalSuppressionTimeout = setTimeout(releaseProvisionalSuppression, PROVISIONAL_SUPPRESSION_TIMEOUT_MS)
  }

  document.addEventListener('asbplayer-native-captions-decline', () => {
    releaseProvisionalSuppression()
  })

  document.addEventListener('asbplayer-native-captions-bind', () => {
    captionControlBound = true
    armedTrackVideoId = inferVideoId()
    // The bound suppression owns the style from here; drop the provisional
    // timer so it can't fire mid-bind.
    releaseProvisionalSuppression()
    suppressNativeCaptionsRendering(true)
    ensureCaptionsButtonObserver()
    publishNativeCaptionsState(true)
  })

  document.addEventListener('asbplayer-native-captions-unbind', () => {
    const boundVideoId = armedTrackVideoId
    captionControlBound = false
    armedTrackVideoId = undefined
    requestedTrackTriple = undefined

    // An unbind that is part of an SPA navigation (the content script resets
    // subtitles before reloading for the incoming video) must not flash that
    // video's native captions: transition straight into a provisional hide. A
    // same-video unbind (the user unloaded subtitles) reveals immediately.
    const videoId = watchPageVideoId()

    if (videoId !== undefined && videoId !== boundVideoId) {
      provisionalVideoId = undefined
      applyProvisionalSuppression()
    } else {
      releaseProvisionalSuppression()
      suppressNativeCaptionsRendering(false)
    }
  })

  document.addEventListener('asbplayer-native-captions-set', (e) => {
    const on = (e as CustomEvent).detail === true

    try {
      const player = moviePlayer()

      if (player?.isSubtitlesOn && player.toggleSubtitles && player.isSubtitlesOn() !== on) {
        player.toggleSubtitles()
      }
    } catch (error) {
      console.error(error)
    }

    publishNativeCaptionsState()
  })

  // --- Native gear-menu track mirroring ---
  // Every native track change (gear → Subtitles/CC, including Auto-translate)
  // fetches `/api/timedtext` with the selected (lang, kind, tlang). A
  // PerformanceObserver on resource entries sees those loads regardless of
  // transport — patching window.fetch would miss them, since YouTube captures
  // its network functions at boot, before a content-script-injected patch can
  // land. The extension's own srv3 fetches are filtered out inside
  // timedtextTripleFromUrl.

  // The track the extension asked the native menu to show (write-back). Kept
  // until replaced/unbound: setOption while captions are toggled off
  // force-enables them (live-probed), which would clobber the adopted CC-off
  // state — so the write is deferred and (re-)applied on every CC-on edge.
  let requestedTrackTriple: NativeTrackTriple | undefined

  // What the player itself reports as selected. Undefined while captions are
  // toggled off — getOption('captions','track') returns {} then.
  const currentPlayerTrackTriple = (): NativeTrackTriple | undefined => {
    try {
      const track = moviePlayer()?.getOption?.('captions', 'track')

      if (!track || typeof track.languageCode !== 'string') {
        return undefined
      }

      return {
        lang: track.languageCode,
        asr: track.kind === 'asr',
        tlang: track.translationLanguage?.languageCode || undefined,
      }
    } catch (error) {
      console.error(error)
      return undefined
    }
  }

  const applyRequestedTrack = () => {
    if (requestedTrackTriple === undefined) {
      return
    }

    try {
      const player = moviePlayer()

      if (!player?.setOption || player.isSubtitlesOn?.() !== true) {
        return
      }

      const current = currentPlayerTrackTriple()

      if (current !== undefined && triplesEqual(current, requestedTrackTriple)) {
        return
      }

      player.setOption('captions', 'track', {
        languageCode: requestedTrackTriple.lang,
        ...(requestedTrackTriple.asr === true ? { kind: 'asr' } : {}),
        ...(requestedTrackTriple.tlang ? { translationLanguage: { languageCode: requestedTrackTriple.tlang } } : {}),
      })
    } catch (error) {
      console.error(error)
    }
  }

  document.addEventListener('asbplayer-native-captions-select-track', (e) => {
    const triple = (e as CustomEvent).detail as Partial<NativeTrackTriple> | undefined

    if (!triple || typeof triple.lang !== 'string') {
      return
    }

    requestedTrackTriple = { lang: triple.lang, asr: triple.asr === true, tlang: triple.tlang || undefined }
    // bind (dispatched earlier in the same load) normally arms already; re-arm
    // here so write-back does not depend on that ordering.
    armedTrackVideoId = inferVideoId()
    applyRequestedTrack()
  })

  const timedtextObserver = new PerformanceObserver((entries) => {
    for (const entry of entries.getEntries()) {
      // Regardless of arming/binding: every native timedtext fetch carries the
      // POT the page-context track URLs need (see knownPoToken).
      harvestTimedtextPot(entry.name)

      const triple = timedtextTripleFromUrl(entry.name)

      if (triple === undefined) {
        continue
      }

      if (!captionControlBound || armedTrackVideoId === undefined || armedTrackVideoId !== inferVideoId()) {
        continue
      }

      // Only fetches matching the player's CURRENT selection are real user
      // picks. This drops stale entries — above all YouTube's CC-on restore
      // fetch of its own persisted track, which loses (microtask vs network)
      // against the deferred write-back applied on the same CC-on edge — and
      // superseded fetches from rapid menu picks.
      const current = currentPlayerTrackTriple()

      if (current === undefined || !triplesEqual(current, triple)) {
        continue
      }

      document.dispatchEvent(new CustomEvent('asbplayer-native-captions-track-selected', { detail: triple }))
    }
  })
  timedtextObserver.observe({ type: 'resource', buffered: false })

  let publishing = false

  // This script is injected at document_start: hide the caption window before
  // YouTube can render a first cue, and start the track-list fetch early.
  applyProvisionalSuppression()
  armInnerTubePrefetch()

  // Handle YT shorts: Publish subtitle tracks according to current video ID
  setInterval(async () => {
    // Covers SPA navigations (video-id changes) and, for the prefetch, cold
    // loads where ytcfg wasn't ready at script startup.
    applyProvisionalSuppression()
    armInnerTubePrefetch()

    if (captionControlBound) {
      // Backstop for changes the attribute observer can't see: button node
      // replacement and availability flips on SPA navigation.
      ensureCaptionsButtonObserver()
      publishNativeCaptionsState()
    }

    if (publishing) {
      return
    }

    try {
      publishing = true
      const videoId = inferVideoId()
      if (lastVideoIdDispatched && videoId && lastVideoIdDispatched !== videoId) {
        lastVideoIdDispatched = await publishCurrentTracks({
          targetTranslationLanguageCodes: lastTargetTranslationLanguageCodes,
        })
      }
    } finally {
      publishing = false
    }
  }, 500)
})
